BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "Test" (
	"Id"	INTEGER,
	"Step"	INTEGER,
	"Method"	TEXT NOT NULL,
	"Uri"	TEXT NOT NULL,
	"JsonGetParameters"	TEXT,
	"JsonPostParameters"	TEXT,
	"JsonConnectedUser"	TEXT,
	"ExpectedResponseCode"	TEXT NOT NULL,
	"Query"	TEXT,
	"QueryExpectedResponse"	TEXT,
	PRIMARY KEY("Id")
);
INSERT INTO "Test" VALUES (2,NULL,'POST','/article/delete/@id:[0-9]+','{"id":1}',NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (3,NULL,'GET','/article/@id:[0-9]+','{"id":1}',NULL,NULL,'400',NULL,NULL);
INSERT INTO "Test" VALUES (4,NULL,'POST','/article/@id:[0-9]+','{"id":1}','{"title":"zz"}',NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (5,NULL,'GET','/publish/article/@id:[0-9]+','{"id":1}',NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (6,NULL,'POST','/publish/article/@id:[0-9]+','{"id":1}','{"isSpotlightActive":false}',NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (7,NULL,'GET','/dbbrowser/@table:[A-Za-z0-9_]+','{"table":"zz"}',NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (8,NULL,'GET','/dbbrowser/@table:[A-Za-z0-9_]+/create','{"table":"zz"}',NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (9,NULL,'POST','/dbbrowser/@table:[A-Za-z0-9_]+/create','{"table":"zz"}',NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (10,NULL,'GET','/dbbrowser/@table:[A-Za-z0-9_]+/edit/@id:[0-9]+','{"table":"zz", "id":1}',NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (11,NULL,'POST','/dbbrowser/@table:[A-Za-z0-9_]+/edit/@id:[0-9]+','{"table":"zz", "id":1}',NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (12,NULL,'POST','/dbbrowser/@table:[A-Za-z0-9_]+/delete/@id:[0-9]+','{"table":"zz", "id":1}',NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (13,NULL,'GET','/emails/article/@id:[0-9]+','{"id":1}',NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (14,NULL,'GET','/event/@id:[0-9]+','{"id":1}',NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (15,NULL,'GET','/group/edit/@id:[0-9]+','{"id":1}',NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (16,NULL,'POST','/group/edit/@id:[0-9]+','{"id":1}','{"id":1}',NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (17,NULL,'POST','/group/delete/@id:[0-9]+','{"id":1}',NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (18,NULL,'GET','/data/media/@year:[0-9]+/@month:[0-9]+/@filename','{"id":1,  "year":1, "month":1, "filename":"zz"}',NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (19,NULL,'GET','/navBar/show/article/@id:[0-9]+','{"id":1}',NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (20,NULL,'GET','/person/edit/@id:[0-9]+','{"id":1}',NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (21,NULL,'POST','/person/edit/@id:[0-9]+','{"id":1}','{"id":1}',NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (22,NULL,'POST','/person/delete/@id:[0-9]+','{"id":1}',NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (23,NULL,'GET','/registration/groups/@id:[0-9]+','{"id":1}',NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (24,NULL,'GET','/survey/add/@id:[0-9]+','{"id":1}',NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (25,NULL,'GET','/survey/results/@id:[0-9]+','{"id":1}',NULL,NULL,'400',NULL,NULL);
INSERT INTO "Test" VALUES (26,NULL,'GET','/user/forgotPassword/@encodedEmail','{"encodedEmail":"webmaster@myclub.foo"}',NULL,NULL,'200',NULL,NULL);
INSERT INTO "Test" VALUES (27,NULL,'GET','/user/setPassword/@token:[a-f0-9]+','{"token":"0123456789abcdef0123456789abcdef"}',NULL,NULL,'200',NULL,NULL);
INSERT INTO "Test" VALUES (28,NULL,'POST','/user/setPassword/@token:[a-f0-9]+','{"token":"0123456789abcdef0123456789abcdef"}','{"password":"admin1234"}',NULL,'400',NULL,NULL);
INSERT INTO "Test" VALUES (29,NULL,'GET','/contact/event/@id:[0-9]+','{"id":1}',NULL,NULL,'200',NULL,NULL);
INSERT INTO "Test" VALUES (31,NULL,'POST','/api/media/delete/@year:[0-9]+/@month:[0-9]+/@filename','{"year":1, "month":1, "filename":"zz"}',NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (32,NULL,'GET','/event/chat/@id:[0-9]+','{"id":1}',NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (33,NULL,'GET','/eventTypes/edit/@id:[0-9]+','{"id":1}',NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (34,NULL,'POST','/eventTypes/edit/@id:[0-9]+','{"id":1}','{"id":1}',NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (35,NULL,'POST','/eventTypes/delete/@id:[0-9]+','{"id":1}',NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (36,NULL,'GET','/user/presentation/@id:[0-9]+','{"id":1}',NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (37,NULL,'GET','/api/author/@articleId:[0-9]+','{"articleId":1}',NULL,NULL,'400',NULL,NULL);
INSERT INTO "Test" VALUES (38,NULL,'GET','/api/survey/reply/@id:[0-9]+','{"id":1}',NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (39,NULL,'GET','/api/carousel/@articleId:[0-9]+','{"articleId":1}',NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (43,NULL,'GET','/event/@id:[0-9]+/@token:[a-f0-9]+','{"id":1, "token":"0123456789abcdef0123456789abcdef"}',NULL,NULL,'400',NULL,NULL);
INSERT INTO "Test" VALUES (44,NULL,'GET','/event/@id:[0-9]+/unregister','{"id":1}',NULL,NULL,'400',NULL,NULL);
INSERT INTO "Test" VALUES (45,NULL,'POST','/api/carousel/delete/@id:[0-9]+','{"id":1}',NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (46,NULL,'POST','/api/attribute/delete/@id:[0-9]+','{"id":1}',NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (47,NULL,'GET','/api/attributes-by-event-type/@id:[0-9]+','{"id":1}',NULL,NULL,'200',NULL,NULL);
INSERT INTO "Test" VALUES (48,NULL,'POST','/api/event/delete/@id:[0-9]+','{"id":1}',NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (49,NULL,'POST','/api/event/duplicate/@id:[0-9]+','{"id":1}','{"id":1}',NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (50,NULL,'GET','/api/event/@id:[0-9]+','{"id":1}',NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (51,NULL,'GET','/api/event-needs/@id:[0-9]+','{"id":1}',NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (52,NULL,'POST','/api/need/delete/@id:[0-9]+','{"id":1}',NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (53,NULL,'POST','/api/need/type/delete/@id:[0-9]+','{"id":1}',NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (54,NULL,'GET','/api/needs-by-need-type/@id:[0-9]+','{"id":1}',NULL,NULL,'200',NULL,NULL);
INSERT INTO "Test" VALUES (56,NULL,'POST','/api/navBar/deleteItem/@id:[0-9]+','{"id":1}',NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (57,NULL,'GET','/api/navBar/getItem/@id:[0-9]+','{"id":1}',NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (58,NULL,'GET','/api/personsInGroup/@id:[0-9]+','{"id":1}',NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (59,NULL,'POST','/api/registration/add/@personId:[0-9]+/@groupId:[0-9]+','{"personId":1, "groupId":1}','{"id":1}',NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (60,NULL,'POST','/api/registration/remove/@personId:[0-9]+/@groupId:[0-9]+','{"personId":1, "groupId":1}','{"id":1}',NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (61,NULL,'GET','/event/@id:[0-9]+/register','{"id":1}',NULL,NULL,'400',NULL,NULL);
INSERT INTO "Test" VALUES (63,NULL,'POST','/design/save',NULL,'{"id":1}',NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (64,NULL,'POST','/emails',NULL,'{"dayOfWeek":"zz"}',NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (65,NULL,'POST','/events/guest',NULL,'{"email":"zz"}',NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (66,NULL,'POST','/group/create',NULL,'{"name":"zz"}',NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (67,NULL,'POST','/import',NULL,'{"csvFile":"zz"}',NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (68,NULL,'POST','/user/presentation/edit',NULL,'{"content":"zz"}',NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (69,NULL,'POST','/survey/create',NULL,'{"question":"zz"}',NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (70,NULL,'POST','/user/account',NULL,'{"id":1}',NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (71,NULL,'POST','/user/availabilities',NULL,'{"id":1}',NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (72,NULL,'POST','/user/groups',NULL,'{"id":1}',NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (73,NULL,'POST','/user/preferences',NULL,'{"id":1}',NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (74,NULL,'POST','/user/sign/in',NULL,'{"id":1}',NULL,'400',NULL,NULL);
INSERT INTO "Test" VALUES (75,NULL,'POST','/contact',NULL,'{"name":"zz","email":"user@myclub.foo", "message":"zz"}',NULL,'200',NULL,NULL);
INSERT INTO "Test" VALUES (76,NULL,'POST','/api/design/vote',NULL,'{"id":1}',NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (77,NULL,'POST','/arward',NULL,'{"id":1}',NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (78,NULL,'POST','/api/media/upload',NULL,'{"id":1}',NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (79,NULL,'POST','/api/survey/reply',NULL,'{"id":1}',NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (80,NULL,'POST','/api/carousel/save',NULL,'{"id":1}',NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (81,NULL,'POST','/api/attribute/create',NULL,'{"id":1}',NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (82,NULL,'POST','/api/attribute/update',NULL,'{"id":1}',NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (83,NULL,'POST','/api/need/type/save',NULL,'{"id":1}',NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (84,NULL,'POST','/api/message/add',NULL,'{"id":1}',NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (85,NULL,'POST','/import/headers',NULL,'{"id":1}',NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (86,NULL,'POST','/api/navBar/saveItem',NULL,'{"id":1}',NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (87,NULL,'POST','/api/event/save',NULL,'{"id":1}',NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (88,NULL,'POST','/api/event/updateSupply',NULL,'{"id":1}',NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (89,NULL,'POST','/api/event/sendEmails',NULL,'{"id":1}',NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (90,NULL,'POST','/api/need/save',NULL,'{"id":1}',NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (91,NULL,'POST','/api/message/update',NULL,'{"id":1}',NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (92,NULL,'POST','/api/navBar/updatePositions',NULL,'{"id":1}',NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (93,4040,'POST','/user/sign/in',NULL,'{"email":"badEmail@myclub.foo","password":"wrongPassword" }',NULL,'400',NULL,NULL);
INSERT INTO "Test" VALUES (94,4050,'POST','/user/sign/in',NULL,'{"email":"webmaster@myclub.foo","password":"wrongPassword" }',NULL,'400',NULL,NULL);
INSERT INTO "Test" VALUES (95,4060,'POST','/user/sign/in',NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }',NULL,'200',NULL,NULL);
INSERT INTO "Test" VALUES (96,NULL,'GET','/user/sign/out',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (148,1000,'PUT','/',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (149,1010,'PUT','/admin',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (150,1020,'PUT','/admin/help',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (151,1030,'PUT','/admin/webmaster/help',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (152,1040,'PUT','/analytics',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (153,1050,'PUT','/api/attribute/create',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (154,1060,'PUT','/api/attribute/delete/1',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (155,1070,'PUT','/api/attribute/update',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (156,1080,'PUT','/api/attributes-by-event-type/1',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (157,1090,'PUT','/api/attributes/list',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (158,1100,'PUT','/api/author/1',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (159,1110,'PUT','/api/carousel/1',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (160,1120,'PUT','/api/carousel/delete/1',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (161,1130,'PUT','/api/carousel/save',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (162,1140,'PUT','/api/design/vote',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (163,1150,'PUT','/api/event-needs/1',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (164,1160,'PUT','/api/event/1',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (165,1170,'PUT','/api/event/delete/1',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (166,1180,'PUT','/api/event/duplicate/@id',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (167,1190,'PUT','/api/event/save',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (168,1200,'PUT','/api/event/sendEmails',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (169,1210,'PUT','/api/event/updateSupply',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (170,1220,'PUT','/api/lastVersion',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (171,1230,'PUT','/api/media/delete/1/1/zz',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (172,1240,'PUT','/api/media/upload',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (173,1250,'PUT','/api/message/add',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (174,1260,'PUT','/api/message/delete',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (175,1270,'PUT','/api/message/update',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (176,1280,'PUT','/api/navBar/deleteItem/1',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (177,1290,'PUT','/api/navBar/getItem/1',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (178,1300,'PUT','/api/navBar/saveItem',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (179,1310,'PUT','/api/navBar/updatePositions',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (180,1320,'PUT','/api/needs-by-need-type/1',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (181,1330,'PUT','/api/need/delete/1',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (182,1340,'PUT','/api/need/save',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (183,1350,'PUT','/api/need/type/delete/1',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (184,1360,'PUT','/api/need/type/save',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (185,1370,'PUT','/api/personsInGroup/1',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (186,1380,'PUT','/api/registration/add/1/1',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (187,1390,'PUT','/api/registration/remove/1/1',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (188,1400,'PUT','/api/survey/reply',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (189,1410,'PUT','/api/survey/reply/1',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (190,1420,'PUT','/article/1',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (191,1430,'PUT','/article/create',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (192,1440,'PUT','/article/delete/1',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (193,1450,'PUT','/articles',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (194,1460,'PUT','/articles-rss.xml',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (195,1470,'PUT','/articles/crosstab',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (196,1480,'PUT','/arwards',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (197,1490,'PUT','/contact',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (198,1500,'PUT','/contact/event/1',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (199,1910,'PUT','/logs/crossTab',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (200,1510,'PUT','/data/media/1/1/zz',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (201,1520,'PUT','/dbbrowser',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (202,1530,'PUT','/dbbrowser/zz',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (203,1540,'PUT','/dbbrowser/zz/create',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (204,1550,'PUT','/dbbrowser/zz/delete/1',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (205,1560,'PUT','/dbbrowser/zz/edit/1',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (206,1570,'PUT','/designer',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (207,1580,'PUT','/designer/help',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (208,1590,'PUT','/designs',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (209,1600,'PUT','/design/create',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (210,1610,'PUT','/design/save',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (211,1620,'PUT','/emails',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (212,1630,'PUT','/emails/article/1',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (213,1640,'PUT','/event/1',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (214,1650,'PUT','/event/1/0123456789abcdef0123456789abcdef',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (215,1660,'PUT','/event/1/register',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (216,1670,'PUT','/event/1/unregister',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (217,1680,'PUT','/event/chat/1',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (218,1690,'PUT','/event/location',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (219,1700,'PUT','/eventManager',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (220,1710,'PUT','/eventManager/help',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (221,1720,'PUT','/eventTypes',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (222,1730,'PUT','/eventTypes/create',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (223,1740,'PUT','/eventTypes/delete/1',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (224,1750,'PUT','/eventTypes/edit/1',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (225,1760,'PUT','/events-rss.xml',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (226,1770,'PUT','/events/crosstab',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (227,1780,'PUT','/events/guest',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (228,1790,'PUT','/ffa/search',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (229,1800,'PUT','/group/create',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (230,1810,'PUT','/group/delete/1',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (231,1820,'PUT','/group/edit/1',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (232,1830,'PUT','/groups',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (233,1840,'PUT','/help',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (234,1850,'PUT','/import',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (235,1860,'PUT','/import/headers',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (236,1870,'PUT','/installations',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (237,1880,'PUT','/lastVisits',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (238,1890,'PUT','/legal/notice',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (239,1900,'PUT','/logs',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (240,1920,'PUT','/media/gpxViewer',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (241,1930,'PUT','/media/list',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (242,1940,'PUT','/media/upload',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (243,1950,'PUT','/navBar',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (244,1960,'PUT','/navBar/show/article/1',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (245,1970,'PUT','/navBar/show/arwards',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (246,1980,'PUT','/needs',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (247,1990,'PUT','/nextEvents',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (248,2000,'PUT','/personManager',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (249,2010,'PUT','/personManager/help',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (250,2020,'PUT','/persons',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (251,2030,'PUT','/person/create',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (252,2040,'PUT','/person/delete/1',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (253,2050,'PUT','/person/edit/1',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (254,2060,'PUT','/publish/article/1',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (255,2070,'PUT','/redactor',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (256,2080,'PUT','/redactor/help',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (257,2090,'PUT','/referents',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (258,2100,'PUT','/registration',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (259,2110,'PUT','/registration/groups/1',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (260,2120,'PUT','/settings',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (261,2130,'PUT','/sitemap.xml',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (262,2140,'PUT','/survey/add/1',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (263,2150,'PUT','/survey/create',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (264,2160,'PUT','/survey/results/1',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (265,2170,'PUT','/topArticles',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (266,2180,'PUT','/topPages',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (267,2190,'PUT','/user',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (268,2200,'PUT','/user/account',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (269,2210,'PUT','/user/availabilities',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (270,2220,'PUT','/user/directory',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (271,2230,'PUT','/user/forgotPassword/webmaster%40myclub.foo',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (272,2240,'PUT','/user/groups',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (273,2250,'PUT','/user/help',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (274,2260,'PUT','/user/directory/map',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (275,2270,'PUT','/user/news',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (276,2280,'PUT','/user/notepad',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (277,2290,'PUT','/user/preferences',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (278,2300,'PUT','/user/presentation/1',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (279,2310,'PUT','/user/presentation/edit',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (280,2320,'PUT','/user/setPassword/0123456789abcdef0123456789abcdef',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (281,2330,'PUT','/user/sign/in',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (282,2340,'PUT','/user/sign/out',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (283,2350,'PUT','/user/statistics',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (284,2360,'PUT','/visitorInsights',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (285,2370,'PUT','/visitorInsights/help',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (286,2380,'PUT','/visitors/graf',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (287,2390,'PUT','/webmaster',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (288,2400,'PUT','/weekEvents',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (289,2410,'GET','/',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','200',NULL,NULL);
INSERT INTO "Test" VALUES (290,2420,'GET','/admin',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','200',NULL,NULL);
INSERT INTO "Test" VALUES (291,2430,'GET','/admin/help',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','200',NULL,NULL);
INSERT INTO "Test" VALUES (292,2440,'GET','/admin/webmaster/help',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','200',NULL,NULL);
INSERT INTO "Test" VALUES (293,2450,'GET','/analytics',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (294,2460,'POST','/api/attribute/create',NULL,'{"name":"attribute name", "detail":"attribute detail", "color":"#112233" }','{"email":"webmaster@myclub.foo","password":"admin1234" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (295,2480,'POST','/api/attribute/delete/1',NULL,'{}','{"email":"webmaster@myclub.foo","password":"admin1234" }','403','SELECT * From Attribute','[]');
INSERT INTO "Test" VALUES (296,2470,'POST','/api/attribute/update',NULL,'{"id":1, "name":"attribute name updated", "detail":"attribute detail updated", "color":"#223344" }','{"email":"webmaster@myclub.foo","password":"admin1234" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (297,2490,'GET','/api/attributes-by-event-type/1',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','200',NULL,NULL);
INSERT INTO "Test" VALUES (298,2500,'GET','/api/attributes/list',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','200',NULL,NULL);
INSERT INTO "Test" VALUES (299,2510,'GET','/api/author/1',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','400',NULL,NULL);
INSERT INTO "Test" VALUES (300,2520,'GET','/api/carousel/1',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','400',NULL,NULL);
INSERT INTO "Test" VALUES (301,2530,'POST','/api/carousel/delete/1',NULL,'{}','{"email":"webmaster@myclub.foo","password":"admin1234" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (302,2540,'POST','/api/carousel/save',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','400',NULL,NULL);
INSERT INTO "Test" VALUES (303,2550,'POST','/api/design/vote',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (304,2560,'GET','/api/event-needs/1',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (305,2570,'GET','/api/event/1',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (306,2580,'POST','/api/event/delete/1',NULL,'{}','{"email":"webmaster@myclub.foo","password":"admin1234" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (307,2590,'POST','/api/event/duplicate/1',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (308,2600,'POST','/api/event/save',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (309,2610,'POST','/api/event/sendEmails',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (310,2620,'POST','/api/event/updateSupply',NULL,'{"eventId":1, "needId":1, "supply":1}','{"email":"webmaster@myclub.foo","password":"admin1234" }','400',NULL,NULL);
INSERT INTO "Test" VALUES (311,2630,'GET','/api/lastVersion',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','200',NULL,NULL);
INSERT INTO "Test" VALUES (312,2640,'POST','/api/media/delete/1/1/zz',NULL,'{}','{"email":"webmaster@myclub.foo","password":"admin1234" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (313,2650,'POST','/api/media/upload',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (314,2660,'POST','/api/message/add',NULL,'{"eventId":1, "text":"new message"}','{"email":"webmaster@myclub.foo","password":"admin1234" }','400',NULL,NULL);
INSERT INTO "Test" VALUES (315,2670,'POST','/api/message/delete',NULL,'{"messageId":1}','{"email":"webmaster@myclub.foo","password":"admin1234" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (316,2680,'POST','/api/message/update',NULL,'{"messageId":1, "text":"message updated"}','{"email":"webmaster@myclub.foo","password":"admin1234" }','400',NULL,NULL);
INSERT INTO "Test" VALUES (317,2690,'POST','/api/navBar/deleteItem/1',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (318,2700,'GET','/api/navBar/getItem/1',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (319,2710,'POST','/api/navBar/saveItem',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (320,2720,'POST','/api/navBar/updatePositions',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (321,2770,'GET','/api/needs-by-need-type/1',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','200',NULL,NULL);
INSERT INTO "Test" VALUES (322,2730,'POST','/api/need/delete/1',NULL,'{}','{"email":"webmaster@myclub.foo","password":"admin1234" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (323,2740,'POST','/api/need/save',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (324,2750,'POST','/api/need/type/delete/1',NULL,'{}','{"email":"webmaster@myclub.foo","password":"admin1234" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (325,2760,'POST','/api/need/type/save',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (326,2780,'GET','/api/personsInGroup/1',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','200',NULL,NULL);
INSERT INTO "Test" VALUES (327,2790,'POST','/api/registration/add/1/1',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','400',NULL,NULL);
INSERT INTO "Test" VALUES (328,2800,'POST','/api/registration/remove/1/1',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','400',NULL,NULL);
INSERT INTO "Test" VALUES (329,2810,'POST','/api/survey/reply',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','400',NULL,NULL);
INSERT INTO "Test" VALUES (330,2820,'GET','/api/survey/reply/1',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','400',NULL,NULL);
INSERT INTO "Test" VALUES (331,2830,'GET','/article/1',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','400',NULL,NULL);
INSERT INTO "Test" VALUES (332,2850,'GET','/article/create',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (333,2860,'POST','/article/delete/1',NULL,'{}','{"email":"webmaster@myclub.foo","password":"admin1234" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (334,2870,'GET','/articles',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','200',NULL,NULL);
INSERT INTO "Test" VALUES (335,2880,'GET','/articles-rss.xml',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','200',NULL,NULL);
INSERT INTO "Test" VALUES (336,2890,'GET','/articles/crosstab',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (337,2910,'GET','/arwards',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (338,2920,'GET','/contact',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','200',NULL,NULL);
INSERT INTO "Test" VALUES (339,2940,'GET','/contact/event/1',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','200',NULL,NULL);
INSERT INTO "Test" VALUES (340,3430,'GET','/logs/crossTab',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (341,2950,'GET','/data/media/1/1/zz',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (342,2960,'GET','/dbbrowser',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','200',NULL,NULL);
INSERT INTO "Test" VALUES (343,2970,'GET','/dbbrowser/zz',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','200',NULL,NULL);
INSERT INTO "Test" VALUES (344,2980,'GET','/dbbrowser/zz/create',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','200',NULL,NULL);
INSERT INTO "Test" VALUES (345,3000,'POST','/dbbrowser/zz/delete/1',NULL,'{}','{"email":"webmaster@myclub.foo","password":"admin1234" }','200',NULL,NULL);
INSERT INTO "Test" VALUES (346,3010,'GET','/dbbrowser/zz/edit/1',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','200',NULL,NULL);
INSERT INTO "Test" VALUES (347,3030,'GET','/designer',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (348,3040,'GET','/designer/help',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (349,3050,'GET','/designs',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (350,3060,'GET','/design/create',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (351,3070,'POST','/design/save',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (352,3080,'GET','/emails',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (353,3100,'GET','/emails/article/1',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (354,3110,'GET','/event/1',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (355,3120,'GET','/event/1/0123456789abcdef0123456789abcdef',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','400',NULL,NULL);
INSERT INTO "Test" VALUES (356,3130,'GET','/event/1/register',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','400',NULL,NULL);
INSERT INTO "Test" VALUES (357,3140,'GET','/event/1/unregister',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','400',NULL,NULL);
INSERT INTO "Test" VALUES (358,3150,'GET','/event/chat/1',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','400',NULL,NULL);
INSERT INTO "Test" VALUES (359,3160,'GET','/event/location',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (360,3170,'GET','/eventManager',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (361,3180,'GET','/eventManager/help',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (362,3190,'GET','/eventTypes',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (363,3200,'GET','/eventTypes/create',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (364,3210,'POST','/eventTypes/delete/1',NULL,'{}','{"email":"webmaster@myclub.foo","password":"admin1234" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (365,3220,'GET','/eventTypes/edit/1',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (366,3240,'GET','/events-rss.xml',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','200',NULL,NULL);
INSERT INTO "Test" VALUES (367,3250,'GET','/events/crosstab',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (368,3260,'GET','/events/guest',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (369,3280,'GET','/ffa/search',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','200',NULL,NULL);
INSERT INTO "Test" VALUES (370,3290,'GET','/group/create',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','200',NULL,NULL);
INSERT INTO "Test" VALUES (371,3310,'POST','/group/delete/1',NULL,'{}','{"email":"webmaster@myclub.foo","password":"admin1234" }','400',NULL,NULL);
INSERT INTO "Test" VALUES (372,3320,'GET','/group/edit/1',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','400',NULL,NULL);
INSERT INTO "Test" VALUES (373,3340,'GET','/groups',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','200',NULL,NULL);
INSERT INTO "Test" VALUES (374,3350,'GET','/help',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','200',NULL,NULL);
INSERT INTO "Test" VALUES (375,3360,'GET','/import',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (376,3380,'POST','/import/headers',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (377,3390,'GET','/installations',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','200',NULL,NULL);
INSERT INTO "Test" VALUES (378,3400,'GET','/lastVisits',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (379,3410,'GET','/legal/notice',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','200',NULL,NULL);
INSERT INTO "Test" VALUES (380,3420,'GET','/logs',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (381,3440,'GET','/media/gpxViewer',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','200',NULL,NULL);
INSERT INTO "Test" VALUES (382,3450,'GET','/media/list',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (383,3460,'GET','/media/upload',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (384,3470,'GET','/navBar',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (385,3480,'GET','/navBar/show/article/1',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (386,3490,'GET','/navBar/show/arwards',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (387,3500,'GET','/needs',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (388,3510,'GET','/nextEvents',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','200',NULL,NULL);
INSERT INTO "Test" VALUES (389,3520,'GET','/personManager',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (390,3530,'GET','/personManager/help',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (391,3540,'GET','/persons',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (392,3550,'GET','/person/create',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (393,3560,'POST','/person/delete/1',NULL,'{}','{"email":"webmaster@myclub.foo","password":"admin1234" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (394,3570,'GET','/person/edit/1',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (395,3590,'GET','/publish/article/1',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (396,3610,'GET','/redactor',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (397,3620,'GET','/redactor/help',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (398,3630,'GET','/referents',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (399,3640,'GET','/registration',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','200',NULL,NULL);
INSERT INTO "Test" VALUES (400,3650,'GET','/registration/groups/1',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','200',NULL,NULL);
INSERT INTO "Test" VALUES (401,3660,'GET','/settings',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (402,3680,'GET','/sitemap.xml',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','200',NULL,NULL);
INSERT INTO "Test" VALUES (403,3690,'GET','/survey/add/1',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (404,3700,'POST','/survey/create',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (405,3710,'GET','/survey/results/1',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','400',NULL,NULL);
INSERT INTO "Test" VALUES (406,3720,'GET','/topArticles',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (407,3730,'GET','/topPages',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (408,3740,'GET','/user',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','200',NULL,NULL);
INSERT INTO "Test" VALUES (409,3750,'GET','/user/account',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','200',NULL,NULL);
INSERT INTO "Test" VALUES (410,3770,'GET','/user/availabilities',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','200',NULL,NULL);
INSERT INTO "Test" VALUES (411,3790,'GET','/user/directory',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','200',NULL,NULL);
INSERT INTO "Test" VALUES (412,3800,'GET','/user/forgotPassword/webmaster%40myclub.foo',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','200',NULL,NULL);
INSERT INTO "Test" VALUES (413,3810,'GET','/user/groups',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','200','SELECT "Group".Name From "Group" INNER JOIN PersonGroup pg ON pg.IdPerson = 1 AND pg.IdGroup = "Group".Id','[{"Name":"Webmaster"}]');
INSERT INTO "Test" VALUES (414,3830,'GET','/user/help',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','200',NULL,NULL);
INSERT INTO "Test" VALUES (415,3840,'GET','/user/directory/map',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','200',NULL,NULL);
INSERT INTO "Test" VALUES (416,3850,'GET','/user/news',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','200',NULL,NULL);
INSERT INTO "Test" VALUES (417,3860,'GET','/user/notepad',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','200',NULL,NULL);
INSERT INTO "Test" VALUES (418,3880,'GET','/user/preferences',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','200',NULL,NULL);
INSERT INTO "Test" VALUES (419,3900,'GET','/user/presentation/1',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','400',NULL,NULL);
INSERT INTO "Test" VALUES (420,3910,'GET','/user/presentation/edit',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','200',NULL,NULL);
INSERT INTO "Test" VALUES (421,3930,'GET','/user/setPassword/0123456789abcdef0123456789abcdef',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','200',NULL,NULL);
INSERT INTO "Test" VALUES (422,3950,'GET','/user/sign/in',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','200',NULL,NULL);
INSERT INTO "Test" VALUES (423,3970,'GET','/user/sign/out',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','200',NULL,NULL);
INSERT INTO "Test" VALUES (424,3980,'GET','/user/statistics',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','200',NULL,NULL);
INSERT INTO "Test" VALUES (425,3990,'GET','/visitorInsights',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (426,4000,'GET','/visitorInsights/help',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (427,4010,'GET','/visitors/graf',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (428,4020,'GET','/webmaster',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','200',NULL,NULL);
INSERT INTO "Test" VALUES (429,4030,'GET','/weekEvents',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','200',NULL,NULL);
INSERT INTO "Test" VALUES (430,2840,'POST','/article/1',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (431,2900,'POST','/arward',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (432,2930,'POST','/contact',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','200',NULL,NULL);
INSERT INTO "Test" VALUES (433,2990,'POST','/dbbrowser/zz/create',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','200',NULL,NULL);
INSERT INTO "Test" VALUES (434,3020,'POST','/dbbrowser/zz/edit/1',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','200',NULL,NULL);
INSERT INTO "Test" VALUES (435,3090,'POST','/emails',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (436,3230,'POST','/eventTypes/edit/1',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (437,3270,'POST','/events/guest',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (438,3300,'POST','/group/create',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','200',NULL,NULL);
INSERT INTO "Test" VALUES (439,3330,'POST','/group/edit/1',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','400',NULL,NULL);
INSERT INTO "Test" VALUES (440,3370,'POST','/import',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (441,3580,'POST','/person/edit/1',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (442,3600,'POST','/publish/article/1',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (443,3670,'POST','/settings',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (444,3760,'POST','/user/account',NULL,'{"email":"webmaster@myclub.foo", "firstName":"first name updated","lastName": "last name updated", "nickName": "nickname updated", "avatar":"\ud83e\udd20"}','{"email":"webmaster@myclub.foo","password":"admin1234" }','200','SELECT FirstName, LastName, NickName, Avatar, UseGravatar From Person','[{"FirstName":"first name updated","LastName":"last name updated","NickName":"nickname updated","Avatar":"🤠","UseGravatar":"no"}]');
INSERT INTO "Test" VALUES (445,3780,'POST','/user/availabilities',NULL,'{"availabilities": {"4": {"morning": "on"}, "5": {"morning": "on"}, "0": {"evening": "on"}, "2": {"evening": "on"}}}','{"email":"webmaster@myclub.foo","password":"admin1234" }','200','SELECT Availabilities From Person','[{"Availabilities":"{\"4\":{\"morning\":\"on\"},\"5\":{\"morning\":\"on\"},\"0\":{\"evening\":\"on\"},\"2\":{\"evening\":\"on\"}}"}]');
INSERT INTO "Test" VALUES (446,3820,'POST','/user/groups',NULL,'[]','{"email":"webmaster@myclub.foo","password":"admin1234" }','200','SELECT "Group".Name From "Group" INNER JOIN PersonGroup pg ON pg.IdPerson = 1 AND pg.IdGroup = "Group".Id','[{"Name":"Webmaster"}]');
INSERT INTO "Test" VALUES (447,3870,'POST','/user/notepad',NULL,'{"content": "<p>my notes<\/p>"}','{"email":"webmaster@myclub.foo","password":"admin1234" }','200','SELECT Notepad From Person','[{"Notepad":"<p>my notes<\/p>"}]');
INSERT INTO "Test" VALUES (448,3890,'POST','/user/preferences',NULL,'[]','{"email":"webmaster@myclub.foo","password":"admin1234" }','200','SELECT Preferences From Person','[{"Preferences":"\"\""}]');
INSERT INTO "Test" VALUES (449,3920,'POST','/user/presentation/edit',NULL,'{"content": "<p>it''''s me at Dijon under the gate<\/p>", "location": "47.323270217558374,5.0347450375556955"}','{"email":"webmaster@myclub.foo","password":"admin1234" }','200','SELECT Presentation, Location From Person','[{"Presentation":"<p>it''''s me at Dijon under the gate<\/p>","Location":"47.323270217558374,5.0347450375556955"}]');
INSERT INTO "Test" VALUES (450,3940,'POST','/user/setPassword/0123456789abcdef0123456789abcdef',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','400',NULL,NULL);
INSERT INTO "Test" VALUES (451,3960,'POST','/user/sign/in',NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','{"email":"webmaster@myclub.foo","password":"admin1234" }','200',NULL,NULL);
INSERT INTO "Test" VALUES (452,4070,'GET','/',NULL,NULL,NULL,'200',NULL,NULL);
INSERT INTO "Test" VALUES (453,4080,'GET','/admin',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (454,4090,'GET','/admin/help',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (455,4100,'GET','/admin/webmaster/help',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (456,4110,'GET','/analytics',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (457,4120,'POST','/api/attribute/create',NULL,'{"name":"attribute name", "detail":"attribute detail", "color":"#112233" }',NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (458,4140,'POST','/api/attribute/delete/1',NULL,'{}',NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (459,4130,'POST','/api/attribute/update',NULL,'{"id":1, "name":"attribute name updated", "detail":"attribute detail updated", "color":"#223344" }',NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (460,4150,'GET','/api/attributes-by-event-type/1',NULL,NULL,NULL,'200',NULL,NULL);
INSERT INTO "Test" VALUES (461,4160,'GET','/api/attributes/list',NULL,NULL,NULL,'200',NULL,NULL);
INSERT INTO "Test" VALUES (462,4170,'GET','/api/author/1',NULL,NULL,NULL,'400',NULL,NULL);
INSERT INTO "Test" VALUES (463,4180,'GET','/api/carousel/1',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (464,4190,'POST','/api/carousel/delete/1',NULL,'{}',NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (465,4200,'POST','/api/carousel/save',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (466,4210,'POST','/api/design/vote',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (467,4220,'GET','/api/event-needs/1',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (468,4230,'GET','/api/event/1',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (469,4240,'POST','/api/event/delete/1',NULL,'{}',NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (470,4250,'POST','/api/event/duplicate/1',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (471,4260,'POST','/api/event/save',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (472,4270,'POST','/api/event/sendEmails',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (473,4280,'POST','/api/event/updateSupply',NULL,'{"eventId":1, "needId":1, "supply":1}',NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (474,4290,'GET','/api/lastVersion',NULL,NULL,NULL,'200',NULL,NULL);
INSERT INTO "Test" VALUES (475,4300,'POST','/api/media/delete/1/1/zz',NULL,'{}',NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (476,4310,'POST','/api/media/upload',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (477,4320,'POST','/api/message/add',NULL,'{"eventId":1, "text":"new message"}',NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (478,4330,'POST','/api/message/delete',NULL,'{"messageId":1}',NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (479,4340,'POST','/api/message/update',NULL,'{"messageId":1, "text":"message updated"}',NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (480,4350,'POST','/api/navBar/deleteItem/1',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (481,4360,'GET','/api/navBar/getItem/1',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (482,4370,'POST','/api/navBar/saveItem',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (483,4380,'POST','/api/navBar/updatePositions',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (484,4430,'GET','/api/needs-by-need-type/1',NULL,NULL,NULL,'200',NULL,NULL);
INSERT INTO "Test" VALUES (485,4390,'POST','/api/need/delete/1',NULL,'{}',NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (486,4400,'POST','/api/need/save',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (487,4410,'POST','/api/need/type/delete/1',NULL,'{}',NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (488,4420,'POST','/api/need/type/save',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (489,4440,'GET','/api/personsInGroup/1',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (490,4450,'POST','/api/registration/add/1/1',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (491,4460,'POST','/api/registration/remove/1/1',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (492,4470,'POST','/api/survey/reply',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (493,4480,'GET','/api/survey/reply/1',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (494,4490,'GET','/article/1',NULL,NULL,NULL,'400',NULL,NULL);
INSERT INTO "Test" VALUES (495,4510,'GET','/article/create',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (496,4520,'POST','/article/delete/1',NULL,'{}',NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (497,4530,'GET','/articles',NULL,NULL,NULL,'200',NULL,NULL);
INSERT INTO "Test" VALUES (498,4540,'GET','/articles-rss.xml',NULL,NULL,NULL,'200',NULL,NULL);
INSERT INTO "Test" VALUES (499,4550,'GET','/articles/crosstab',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (500,4570,'GET','/arwards',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (501,4580,'GET','/contact',NULL,NULL,NULL,'200',NULL,NULL);
INSERT INTO "Test" VALUES (502,4600,'GET','/contact/event/1',NULL,NULL,NULL,'200',NULL,NULL);
INSERT INTO "Test" VALUES (503,5090,'GET','/logs/crossTab',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (504,4610,'GET','/data/media/1/1/zz',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (505,4620,'GET','/dbbrowser',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (506,4630,'GET','/dbbrowser/zz',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (507,4640,'GET','/dbbrowser/zz/create',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (508,4660,'POST','/dbbrowser/zz/delete/1',NULL,'{}',NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (509,4670,'GET','/dbbrowser/zz/edit/1',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (510,4690,'GET','/designer',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (511,4700,'GET','/designer/help',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (512,4710,'GET','/designs',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (513,4720,'GET','/design/create',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (514,4730,'POST','/design/save',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (515,4740,'GET','/emails',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (516,4760,'GET','/emails/article/1',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (517,4770,'GET','/event/1',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (518,4780,'GET','/event/1/0123456789abcdef0123456789abcdef',NULL,NULL,NULL,'400',NULL,NULL);
INSERT INTO "Test" VALUES (519,4790,'GET','/event/1/register',NULL,NULL,NULL,'400',NULL,NULL);
INSERT INTO "Test" VALUES (520,4800,'GET','/event/1/unregister',NULL,NULL,NULL,'400',NULL,NULL);
INSERT INTO "Test" VALUES (521,4810,'GET','/event/chat/1',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (522,4820,'GET','/event/location',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (523,4830,'GET','/eventManager',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (524,4840,'GET','/eventManager/help',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (525,4850,'GET','/eventTypes',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (526,4860,'GET','/eventTypes/create',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (527,4870,'POST','/eventTypes/delete/1',NULL,'{}',NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (528,4880,'GET','/eventTypes/edit/1',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (529,4900,'GET','/events-rss.xml',NULL,NULL,NULL,'200',NULL,NULL);
INSERT INTO "Test" VALUES (530,4910,'GET','/events/crosstab',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (531,4920,'GET','/events/guest',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (532,4940,'GET','/ffa/search',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (533,4950,'GET','/group/create',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (534,4970,'POST','/group/delete/1',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (535,4980,'GET','/group/edit/1',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (536,5000,'GET','/groups',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (537,5010,'GET','/help',NULL,NULL,NULL,'200',NULL,NULL);
INSERT INTO "Test" VALUES (538,5020,'GET','/import',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (539,5040,'POST','/import/headers',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (540,5050,'GET','/installations',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (541,5060,'GET','/lastVisits',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (542,5070,'GET','/legal/notice',NULL,NULL,NULL,'200',NULL,NULL);
INSERT INTO "Test" VALUES (543,5080,'GET','/logs',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (544,5100,'GET','/media/gpxViewer',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (545,5110,'GET','/media/list',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (546,5120,'GET','/media/upload',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (547,5130,'GET','/navBar',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (548,5140,'GET','/navBar/show/article/1',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (549,5150,'GET','/navBar/show/arwards',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (550,5160,'GET','/needs',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (551,5170,'GET','/nextEvents',NULL,NULL,NULL,'200',NULL,NULL);
INSERT INTO "Test" VALUES (552,5180,'GET','/personManager',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (553,5190,'GET','/personManager/help',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (554,5200,'GET','/persons',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (555,5210,'GET','/person/create',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (556,5220,'POST','/person/delete/1',NULL,'{}',NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (557,5230,'GET','/person/edit/1',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (558,5250,'GET','/publish/article/1',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (559,5270,'GET','/redactor',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (560,5280,'GET','/redactor/help',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (561,5290,'GET','/referents',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (562,5300,'GET','/registration',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (563,5310,'GET','/registration/groups/1',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (564,5320,'GET','/settings',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (565,5340,'GET','/sitemap.xml',NULL,NULL,NULL,'200',NULL,NULL);
INSERT INTO "Test" VALUES (566,5350,'GET','/survey/add/1',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (567,5360,'POST','/survey/create',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (568,5370,'GET','/survey/results/1',NULL,NULL,NULL,'400',NULL,NULL);
INSERT INTO "Test" VALUES (569,5380,'GET','/topArticles',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (570,5390,'GET','/topPages',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (571,5400,'GET','/user',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (572,5410,'GET','/user/account',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (573,5430,'GET','/user/availabilities',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (574,5450,'GET','/user/directory',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (575,5460,'GET','/user/forgotPassword/webmaster%40myclub.foo',NULL,NULL,NULL,'200',NULL,NULL);
INSERT INTO "Test" VALUES (576,5470,'GET','/user/groups',NULL,NULL,NULL,'403','SELECT "Group".Name From "Group" INNER JOIN PersonGroup pg ON pg.IdPerson = 1 AND pg.IdGroup = "Group".Id','[{"Name":"Webmaster"}]');
INSERT INTO "Test" VALUES (577,5490,'GET','/user/help',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (578,5500,'GET','/user/directory/map',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (579,5510,'GET','/user/news',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (580,5520,'GET','/user/notepad',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (581,5540,'GET','/user/preferences',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (582,5560,'GET','/user/presentation/1',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (583,5570,'GET','/user/presentation/edit',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (584,5590,'GET','/user/setPassword/0123456789abcdef0123456789abcdef',NULL,NULL,NULL,'200',NULL,NULL);
INSERT INTO "Test" VALUES (585,5610,'GET','/user/sign/in',NULL,NULL,NULL,'200',NULL,NULL);
INSERT INTO "Test" VALUES (586,5630,'GET','/user/sign/out',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (587,5640,'GET','/user/statistics',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (588,5650,'GET','/visitorInsights',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (589,5660,'GET','/visitorInsights/help',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (590,5670,'GET','/visitors/graf',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (591,5680,'GET','/webmaster',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (592,5690,'GET','/weekEvents',NULL,NULL,NULL,'200',NULL,NULL);
INSERT INTO "Test" VALUES (593,4500,'POST','/article/1',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (594,4560,'POST','/arward',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (595,4590,'POST','/contact',NULL,NULL,NULL,'200',NULL,NULL);
INSERT INTO "Test" VALUES (596,4650,'POST','/dbbrowser/zz/create',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (597,4680,'POST','/dbbrowser/zz/edit/1',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (598,4750,'POST','/emails',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (599,4890,'POST','/eventTypes/edit/1',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (600,4930,'POST','/events/guest',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (601,4960,'POST','/group/create',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (602,4990,'POST','/group/edit/1',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (603,5030,'POST','/import',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (604,5240,'POST','/person/edit/1',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (605,5260,'POST','/publish/article/1',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (606,5330,'POST','/settings',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (607,5420,'POST','/user/account',NULL,'{"email":"webmaster@myclub.foo", "firstName":"first name updated","lastName": "last name updated", "nickName": "nickname updated", "avatar":"\ud83e\udd20"}',NULL,'403','SELECT FirstName, LastName, NickName, Avatar, UseGravatar From Person','[{"FirstName":"first name updated","LastName":"last name updated","NickName":"nickname updated","Avatar":"🤠","UseGravatar":"no"}]');
INSERT INTO "Test" VALUES (608,5440,'POST','/user/availabilities',NULL,'{"availabilities": {"4": {"morning": "on"}, "5": {"morning": "on"}, "0": {"evening": "on"}, "2": {"evening": "on"}}}',NULL,'403','SELECT Availabilities From Person','[{"Availabilities":"{\"4\":{\"morning\":\"on\"},\"5\":{\"morning\":\"on\"},\"0\":{\"evening\":\"on\"},\"2\":{\"evening\":\"on\"}}"}]');
INSERT INTO "Test" VALUES (609,5480,'POST','/user/groups',NULL,'[]',NULL,'403','SELECT "Group".Name From "Group" INNER JOIN PersonGroup pg ON pg.IdPerson = 1 AND pg.IdGroup = "Group".Id','[{"Name":"Webmaster"}]');
INSERT INTO "Test" VALUES (610,5530,'POST','/user/notepad',NULL,'{"content": "<p>my notes<\/p>"}',NULL,'403','SELECT Notepad From Person','[{"Notepad":"<p>my notes<\/p>"}]');
INSERT INTO "Test" VALUES (611,5550,'POST','/user/preferences',NULL,'[]',NULL,'403','SELECT Preferences From Person','[{"Preferences":"\"\""}]');
INSERT INTO "Test" VALUES (612,5580,'POST','/user/presentation/edit',NULL,'{"content": "<p>it''''s me at Dijon under the gate<\/p>", "location": "47.323270217558374,5.0347450375556955"}',NULL,'403','SELECT Presentation, Location From Person','[{"Presentation":"<p>it''''s me at Dijon under the gate<\/p>","Location":"47.323270217558374,5.0347450375556955"}]');
INSERT INTO "Test" VALUES (613,5600,'POST','/user/setPassword/0123456789abcdef0123456789abcdef',NULL,NULL,NULL,'400',NULL,NULL);
INSERT INTO "Test" VALUES (614,5620,'POST','/user/sign/in',NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }',NULL,'200',NULL,NULL);
INSERT INTO "Test" VALUES (615,102410,'GET','/',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','200','','');
INSERT INTO "Test" VALUES (616,102420,'GET','/admin',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','200',NULL,NULL);
INSERT INTO "Test" VALUES (617,102430,'GET','/admin/help',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','200',NULL,NULL);
INSERT INTO "Test" VALUES (618,102440,'GET','/admin/webmaster/help',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','200',NULL,NULL);
INSERT INTO "Test" VALUES (619,102450,'GET','/analytics',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (620,102460,'POST','/api/attribute/create',NULL,'{"name":"attribute name", "detail":"attribute detail", "color":"#112233" }','{"email":"personManager@myclub.foo","password":"personManager3456" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (621,102480,'POST','/api/attribute/delete/1',NULL,'{}','{"email":"personManager@myclub.foo","password":"personManager3456" }','403','SELECT * From Attribute','[]');
INSERT INTO "Test" VALUES (622,102470,'POST','/api/attribute/update',NULL,'{"id":1, "name":"attribute name updated", "detail":"attribute detail updated", "color":"#223344" }','{"email":"personManager@myclub.foo","password":"personManager3456" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (623,102490,'GET','/api/attributes-by-event-type/1',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','200',NULL,NULL);
INSERT INTO "Test" VALUES (624,102500,'GET','/api/attributes/list',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','200',NULL,NULL);
INSERT INTO "Test" VALUES (625,102510,'GET','/api/author/1',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','400',NULL,NULL);
INSERT INTO "Test" VALUES (626,102520,'GET','/api/carousel/1',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','400',NULL,NULL);
INSERT INTO "Test" VALUES (627,102530,'POST','/api/carousel/delete/1',NULL,'{}','{"email":"personManager@myclub.foo","password":"personManager3456" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (628,102540,'POST','/api/carousel/save',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','400',NULL,NULL);
INSERT INTO "Test" VALUES (629,102550,'POST','/api/design/vote',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (630,102560,'GET','/api/event-needs/1',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (631,102570,'GET','/api/event/1',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (632,102580,'POST','/api/event/delete/1',NULL,'{}','{"email":"personManager@myclub.foo","password":"personManager3456" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (633,102590,'POST','/api/event/duplicate/1',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (634,102600,'POST','/api/event/save',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (635,102610,'POST','/api/event/sendEmails',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (636,102620,'POST','/api/event/updateSupply',NULL,'{"eventId":1, "needId":1, "supply":1}','{"email":"personManager@myclub.foo","password":"personManager3456" }','400',NULL,NULL);
INSERT INTO "Test" VALUES (637,102630,'GET','/api/lastVersion',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','200',NULL,NULL);
INSERT INTO "Test" VALUES (638,102640,'POST','/api/media/delete/1/1/zz',NULL,'{}','{"email":"personManager@myclub.foo","password":"personManager3456" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (639,102650,'POST','/api/media/upload',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (640,102660,'POST','/api/message/add',NULL,'{"eventId":1, "text":"new message"}','{"email":"personManager@myclub.foo","password":"personManager3456" }','400',NULL,NULL);
INSERT INTO "Test" VALUES (641,102670,'POST','/api/message/delete',NULL,'{"messageId":1}','{"email":"personManager@myclub.foo","password":"personManager3456" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (642,102680,'POST','/api/message/update',NULL,'{"messageId":1, "text":"message updated"}','{"email":"personManager@myclub.foo","password":"personManager3456" }','400',NULL,NULL);
INSERT INTO "Test" VALUES (643,102690,'POST','/api/navBar/deleteItem/1',NULL,'{}','{"email":"personManager@myclub.foo","password":"personManager3456" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (644,102700,'GET','/api/navBar/getItem/1',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (645,102710,'POST','/api/navBar/saveItem',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (646,102720,'POST','/api/navBar/updatePositions',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (647,102770,'GET','/api/needs-by-need-type/1',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','200',NULL,NULL);
INSERT INTO "Test" VALUES (648,102730,'POST','/api/need/delete/1',NULL,'{}','{"email":"personManager@myclub.foo","password":"personManager3456" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (649,102740,'POST','/api/need/save',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (650,102750,'POST','/api/need/type/delete/1',NULL,'{}','{"email":"personManager@myclub.foo","password":"personManager3456" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (651,102760,'POST','/api/need/type/save',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (652,102780,'GET','/api/personsInGroup/1',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','200',NULL,NULL);
INSERT INTO "Test" VALUES (653,102790,'POST','/api/registration/add/1/1',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','400',NULL,NULL);
INSERT INTO "Test" VALUES (654,102800,'POST','/api/registration/remove/1/1',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','400',NULL,NULL);
INSERT INTO "Test" VALUES (655,102810,'POST','/api/survey/reply',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','400',NULL,NULL);
INSERT INTO "Test" VALUES (656,102820,'GET','/api/survey/reply/1',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','400',NULL,NULL);
INSERT INTO "Test" VALUES (657,102830,'GET','/article/1',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','400',NULL,NULL);
INSERT INTO "Test" VALUES (658,102850,'GET','/article/create',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (659,102860,'POST','/article/delete/1',NULL,'{}','{"email":"personManager@myclub.foo","password":"personManager3456" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (660,102870,'GET','/articles',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','200',NULL,NULL);
INSERT INTO "Test" VALUES (661,102880,'GET','/articles-rss.xml',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','200',NULL,NULL);
INSERT INTO "Test" VALUES (662,102890,'GET','/articles/crosstab',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (663,102910,'GET','/arwards',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (664,102920,'GET','/contact',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','200',NULL,NULL);
INSERT INTO "Test" VALUES (665,102940,'GET','/contact/event/1',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','200',NULL,NULL);
INSERT INTO "Test" VALUES (666,103430,'GET','/logs/crossTab',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (667,102950,'GET','/data/media/1/1/zz',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (668,102960,'GET','/dbbrowser',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','200',NULL,NULL);
INSERT INTO "Test" VALUES (669,102970,'GET','/dbbrowser/zz',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','200',NULL,NULL);
INSERT INTO "Test" VALUES (670,102980,'GET','/dbbrowser/zz/create',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','200',NULL,NULL);
INSERT INTO "Test" VALUES (671,103000,'POST','/dbbrowser/zz/delete/1',NULL,'{}','{"email":"personManager@myclub.foo","password":"personManager3456" }','200',NULL,NULL);
INSERT INTO "Test" VALUES (672,103010,'GET','/dbbrowser/zz/edit/1',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','200',NULL,NULL);
INSERT INTO "Test" VALUES (673,103030,'GET','/designer',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (674,103040,'GET','/designer/help',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (675,103050,'GET','/designs',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (676,103060,'GET','/design/create',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (677,103070,'POST','/design/save',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (678,103080,'GET','/emails',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (679,103100,'GET','/emails/article/1',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (680,103110,'GET','/event/1',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (681,103120,'GET','/event/1/0123456789abcdef0123456789abcdef',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','400',NULL,NULL);
INSERT INTO "Test" VALUES (682,103130,'GET','/event/1/register',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','400',NULL,NULL);
INSERT INTO "Test" VALUES (683,103140,'GET','/event/1/unregister',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','400',NULL,NULL);
INSERT INTO "Test" VALUES (684,103150,'GET','/event/chat/1',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','400',NULL,NULL);
INSERT INTO "Test" VALUES (685,103160,'GET','/event/location',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (686,103170,'GET','/eventManager',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (687,103180,'GET','/eventManager/help',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (688,103190,'GET','/eventTypes',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (689,103200,'GET','/eventTypes/create',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (690,103210,'POST','/eventTypes/delete/1',NULL,'{}','{"email":"personManager@myclub.foo","password":"personManager3456" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (691,103220,'GET','/eventTypes/edit/1',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (692,103240,'GET','/events-rss.xml',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','200',NULL,NULL);
INSERT INTO "Test" VALUES (693,103250,'GET','/events/crosstab',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (694,103260,'GET','/events/guest',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (695,103280,'GET','/ffa/search',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','200',NULL,NULL);
INSERT INTO "Test" VALUES (696,103290,'GET','/group/create',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','200',NULL,NULL);
INSERT INTO "Test" VALUES (697,103310,'POST','/group/delete/1',NULL,'{}','{"email":"personManager@myclub.foo","password":"personManager3456" }','400',NULL,NULL);
INSERT INTO "Test" VALUES (698,103320,'GET','/group/edit/1',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','400',NULL,NULL);
INSERT INTO "Test" VALUES (699,103340,'GET','/groups',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','200',NULL,NULL);
INSERT INTO "Test" VALUES (700,103350,'GET','/help',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','200',NULL,NULL);
INSERT INTO "Test" VALUES (701,103360,'GET','/import',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (702,103380,'POST','/import/headers',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (703,103390,'GET','/installations',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','200',NULL,NULL);
INSERT INTO "Test" VALUES (704,103400,'GET','/lastVisits',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (705,103410,'GET','/legal/notice',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','200',NULL,NULL);
INSERT INTO "Test" VALUES (706,103420,'GET','/logs',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (707,103440,'GET','/media/gpxViewer',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','200',NULL,NULL);
INSERT INTO "Test" VALUES (708,103450,'GET','/media/list',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (709,103460,'GET','/media/upload',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (710,103470,'GET','/navBar',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (711,103480,'GET','/navBar/show/article/1',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (712,103490,'GET','/navBar/show/arwards',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (713,103500,'GET','/needs',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (714,103510,'GET','/nextEvents',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','200',NULL,NULL);
INSERT INTO "Test" VALUES (715,103520,'GET','/personManager',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (716,103530,'GET','/personManager/help',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (717,103540,'GET','/persons',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (718,103550,'GET','/person/create',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (719,103560,'POST','/person/delete/1',NULL,'{}','{"email":"personManager@myclub.foo","password":"personManager3456" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (720,103570,'GET','/person/edit/1',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (721,103590,'GET','/publish/article/1',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (722,103610,'GET','/redactor',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (723,103620,'GET','/redactor/help',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (724,103630,'GET','/referents',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (725,103640,'GET','/registration',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','200',NULL,NULL);
INSERT INTO "Test" VALUES (726,103650,'GET','/registration/groups/1',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','200',NULL,NULL);
INSERT INTO "Test" VALUES (727,103660,'GET','/settings',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (728,103680,'GET','/sitemap.xml',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','200',NULL,NULL);
INSERT INTO "Test" VALUES (729,103690,'GET','/survey/add/1',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (730,103700,'POST','/survey/create',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (731,103710,'GET','/survey/results/1',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','400',NULL,NULL);
INSERT INTO "Test" VALUES (732,103720,'GET','/topArticles',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (733,103730,'GET','/topPages',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (734,103740,'GET','/user',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','200',NULL,NULL);
INSERT INTO "Test" VALUES (735,103750,'GET','/user/account',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','200',NULL,NULL);
INSERT INTO "Test" VALUES (736,103770,'GET','/user/availabilities',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','200',NULL,NULL);
INSERT INTO "Test" VALUES (737,103790,'GET','/user/directory',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','200',NULL,NULL);
INSERT INTO "Test" VALUES (738,103800,'GET','/user/forgotPassword/webmaster%40myclub.foo',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','200',NULL,NULL);
INSERT INTO "Test" VALUES (739,103810,'GET','/user/groups',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','200','SELECT "Group".Name From "Group" INNER JOIN PersonGroup pg ON pg.IdPerson = 1 AND pg.IdGroup = "Group".Id','[{"Name":"Webmaster"}]');
INSERT INTO "Test" VALUES (740,103830,'GET','/user/help',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','200',NULL,NULL);
INSERT INTO "Test" VALUES (741,103840,'GET','/user/directory/map',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','200',NULL,NULL);
INSERT INTO "Test" VALUES (742,103850,'GET','/user/news',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','200',NULL,NULL);
INSERT INTO "Test" VALUES (743,103860,'GET','/user/notepad',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','200',NULL,NULL);
INSERT INTO "Test" VALUES (744,103880,'GET','/user/preferences',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','200',NULL,NULL);
INSERT INTO "Test" VALUES (745,103900,'GET','/user/presentation/1',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','400',NULL,NULL);
INSERT INTO "Test" VALUES (746,103910,'GET','/user/presentation/edit',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','200',NULL,NULL);
INSERT INTO "Test" VALUES (747,103930,'GET','/user/setPassword/0123456789abcdef0123456789abcdef',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','200',NULL,NULL);
INSERT INTO "Test" VALUES (748,103950,'GET','/user/sign/in',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','200',NULL,NULL);
INSERT INTO "Test" VALUES (749,103970,'GET','/user/sign/out',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','200',NULL,NULL);
INSERT INTO "Test" VALUES (750,103980,'GET','/user/statistics',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','200',NULL,NULL);
INSERT INTO "Test" VALUES (751,103990,'GET','/visitorInsights',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (752,104000,'GET','/visitorInsights/help',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (753,104010,'GET','/visitors/graf',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (754,104020,'GET','/webmaster',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','200',NULL,NULL);
INSERT INTO "Test" VALUES (755,104030,'GET','/weekEvents',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','200',NULL,NULL);
INSERT INTO "Test" VALUES (756,102840,'POST','/article/1',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (757,102900,'POST','/arward',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (758,102930,'POST','/contact',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','200',NULL,NULL);
INSERT INTO "Test" VALUES (759,102990,'POST','/dbbrowser/zz/create',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','200',NULL,NULL);
INSERT INTO "Test" VALUES (760,103020,'POST','/dbbrowser/zz/edit/1',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','200',NULL,NULL);
INSERT INTO "Test" VALUES (761,103090,'POST','/emails',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (762,103230,'POST','/eventTypes/edit/1',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (763,103270,'POST','/events/guest',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (764,103300,'POST','/group/create',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','200',NULL,NULL);
INSERT INTO "Test" VALUES (765,103330,'POST','/group/edit/1',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','400',NULL,NULL);
INSERT INTO "Test" VALUES (766,103370,'POST','/import',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (767,103580,'POST','/person/edit/1',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (768,103600,'POST','/publish/article/1',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (769,103670,'POST','/settings',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (770,103760,'POST','/user/account',NULL,'{"email":"webmaster@myclub.foo", "firstName":"first name updated","lastName": "last name updated", "nickName": "nickname updated", "avatar":"\ud83e\udd20"}','{"email":"personManager@myclub.foo","password":"personManager3456" }','200','SELECT FirstName, LastName, NickName, Avatar, UseGravatar From Person','[{"FirstName":"first name updated","LastName":"last name updated","NickName":"nickname updated","Avatar":"🤠","UseGravatar":"no"}]');
INSERT INTO "Test" VALUES (771,103780,'POST','/user/availabilities',NULL,'{"availabilities": {"4": {"morning": "on"}, "5": {"morning": "on"}, "0": {"evening": "on"}, "2": {"evening": "on"}}}','{"email":"personManager@myclub.foo","password":"personManager3456" }','200','SELECT Availabilities From Person','[{"Availabilities":"{\"4\":{\"morning\":\"on\"},\"5\":{\"morning\":\"on\"},\"0\":{\"evening\":\"on\"},\"2\":{\"evening\":\"on\"}}"}]');
INSERT INTO "Test" VALUES (772,103820,'POST','/user/groups',NULL,'[]','{"email":"personManager@myclub.foo","password":"personManager3456" }','200','SELECT "Group".Name From "Group" INNER JOIN PersonGroup pg ON pg.IdPerson = 1 AND pg.IdGroup = "Group".Id','[{"Name":"Webmaster"}]');
INSERT INTO "Test" VALUES (773,103870,'POST','/user/notepad',NULL,'{"content": "<p>my notes<\/p>"}','{"email":"personManager@myclub.foo","password":"personManager3456" }','200','SELECT Notepad From Person','[{"Notepad":"<p>my notes<\/p>"}]');
INSERT INTO "Test" VALUES (774,103890,'POST','/user/preferences',NULL,'[]','{"email":"personManager@myclub.foo","password":"personManager3456" }','200','SELECT Preferences From Person','[{"Preferences":"\"\""}]');
INSERT INTO "Test" VALUES (775,103920,'POST','/user/presentation/edit',NULL,'{"content": "<p>it''''s me at Dijon under the gate<\/p>", "location": "47.323270217558374,5.0347450375556955"}','{"email":"personManager@myclub.foo","password":"personManager3456" }','200','SELECT Presentation, Location From Person','[{"Presentation":"<p>it''''s me at Dijon under the gate<\/p>","Location":"47.323270217558374,5.0347450375556955"}]');
INSERT INTO "Test" VALUES (776,103940,'POST','/user/setPassword/0123456789abcdef0123456789abcdef',NULL,NULL,'{"email":"personManager@myclub.foo","password":"personManager3456" }','400',NULL,NULL);
INSERT INTO "Test" VALUES (777,103960,'POST','/user/sign/in',NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','{"email":"personManager@myclub.foo","password":"personManager3456" }','200',NULL,NULL);
INSERT INTO "Test" VALUES (778,10000,'POST','/group/create',NULL,'{"name": "Human ressources", "authorizations": ["2"]}','{"email":"webmaster@myclub.foo","password":"admin1234" }','303','SELECT * From "Group"','[{"Id":1,"Name":"Webmaster","Inactivated":0,"SelfRegistration":0},{"Id":2,"Name":"Human ressources","Inactivated":0,"SelfRegistration":0}]');
INSERT INTO "Test" VALUES (779,10010,'POST','/api/registration/add/1/2',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','200','SELECT * From PersonGroup Where IdPerson = 1','[{"Id":1,"IdPerson":1,"IdGroup":1},{"Id":2,"IdPerson":1,"IdGroup":2}]');
INSERT INTO "Test" VALUES (780,10020,'GET','/person/create',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','200','SELECT Id From Person','[{"Id":2},{"Id":1}]');
INSERT INTO "Test" VALUES (781,10030,'POST','/person/edit/2',NULL,'{"email": "personManager@myclub.foo", "firstName": "Person", "lastName": "Manager"}','{"email":"webmaster@myclub.foo","password":"admin1234" }','200','SELECT Email, FirstName, LastName from Person Where Id = 2','[{"Email":"personManager@myclub.foo","FirstName":"Person","LastName":"Manager"}]');
COMMIT;
