BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "Test" (
	"Id"	INTEGER,
	"Step"	INTEGER,
	"Method"	TEXT NOT NULL,
	"Uri"	TEXT NOT NULL,
	"JsonGetParameters"	TEXT,
	"JsonPostParameters"	TEXT,
	"JsonConnectedUser"	TEXT,
	"ExpectedResponseCode"	TEXT NOT NULL,
	"Query"	TEXT,
	"QueryExpectedResponse"	TEXT,
	PRIMARY KEY("Id")
);
INSERT INTO "Test" VALUES (2,NULL,'DELETE','/article/delete/@id:[0-9]+','{"id":1}',NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (3,NULL,'GET','/article/@id:[0-9]+','{"id":1}',NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (4,NULL,'POST','/article/@id:[0-9]+','{"id":1}','{"title":"zz"}',NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (5,NULL,'GET','/publish/article/@id:[0-9]+','{"id":1}',NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (6,NULL,'POST','/publish/article/@id:[0-9]+','{"id":1}','{"isSpotlightActive":false}',NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (7,NULL,'GET','/dbbrowser/@table:[A-Za-z0-9_]+','{"table":"zz"}',NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (8,NULL,'GET','/dbbrowser/@table:[A-Za-z0-9_]+/create','{"table":"zz"}',NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (9,NULL,'POST','/dbbrowser/@table:[A-Za-z0-9_]+/create','{"table":"zz"}','{"id":1}',NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (10,NULL,'GET','/dbbrowser/@table:[A-Za-z0-9_]+/edit/@id:[0-9]+','{"table":"zz", "id":1}',NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (11,NULL,'POST','/dbbrowser/@table:[A-Za-z0-9_]+/edit/@id:[0-9]+','{"table":"zz", "id":1}','{"id":1}',NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (12,NULL,'DELETE','/dbbrowser/@table:[A-Za-z0-9_]+/delete/@id:[0-9]+','{"table":"zz", "id":1}',NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (13,NULL,'GET','/emails/article/@id:[0-9]+','{"id":1}',NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (14,NULL,'GET','/event/@id:[0-9]+','{"id":1}',NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (15,NULL,'GET','/group/edit/@id:[0-9]+','{"id":1}',NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (16,NULL,'POST','/group/edit/@id:[0-9]+','{"id":1}','{"id":1}',NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (17,NULL,'DELETE','/group/delete/@id:[0-9]+','{"id":1}',NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (18,NULL,'GET','/data/media/@year:[0-9]+/@month:[0-9]+/@filename','{"id":1,  "year":1, "month":1, "filename":"zz"}',NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (19,NULL,'GET','/navBar/show/article/@id:[0-9]+','{"id":1}',NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (20,NULL,'GET','/persons/edit/@id:[0-9]+','{"id":1}',NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (21,NULL,'POST','/persons/edit/@id:[0-9]+','{"id":1}','{"id":1}',NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (22,NULL,'DELETE','/persons/delete/@id:[0-9]+','{"id":1}',NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (23,NULL,'GET','/registration/groups/@id:[0-9]+','{"id":1}',NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (24,NULL,'GET','/surveys/add/@id:[0-9]+','{"id":1}',NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (25,NULL,'GET','/surveys/results/@id:[0-9]+','{"id":1}',NULL,NULL,'401',NULL,NULL);
INSERT INTO "Test" VALUES (26,NULL,'GET','/user/forgotPassword/@encodedEmail','{"encodedEmail":"webmaster@myclub.foo"}',NULL,NULL,'200',NULL,NULL);
INSERT INTO "Test" VALUES (27,NULL,'GET','/user/setPassword/@token:[a-f0-9]+','{"token":"0123456789abcdef0123456789abcdef"}',NULL,NULL,'200',NULL,NULL);
INSERT INTO "Test" VALUES (28,NULL,'POST','/user/setPassword/@token:[a-f0-9]+','{"token":"0123456789abcdef0123456789abcdef"}','{"password":"admin1234"}',NULL,'400',NULL,NULL);
INSERT INTO "Test" VALUES (29,NULL,'GET','/contact/event/@id:[0-9]+','{"id":1}',NULL,NULL,'200',NULL,NULL);
INSERT INTO "Test" VALUES (31,NULL,'DELETE','/api/media/delete/@year:[0-9]+/@month:[0-9]+/@filename','{"year":1, "month":1, "filename":"zz"}',NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (32,NULL,'GET','/event/chat/@id:[0-9]+','{"id":1}',NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (33,NULL,'GET','/eventTypes/edit/@id:[0-9]+','{"id":1}',NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (34,NULL,'POST','/eventTypes/edit/@id:[0-9]+','{"id":1}','{"id":1}',NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (35,NULL,'DELETE','/eventTypes/delete/@id:[0-9]+','{"id":1}',NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (36,NULL,'GET','/user/presentation/@id:[0-9]+','{"id":1}',NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (37,NULL,'GET','/api/author/@articleId:[0-9]+','{"articleId":1}',NULL,NULL,'200',NULL,NULL);
INSERT INTO "Test" VALUES (38,NULL,'GET','/api/surveys/reply/@id:[0-9]+','{"id":1}',NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (39,NULL,'GET','/api/carousel/@articleId:[0-9]+','{"articleId":1}',NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (43,NULL,'GET','/event/@id:[0-9]+/@token:[a-f0-9]+','{"id":1, "token":"0123456789abcdef0123456789abcdef"}',NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (44,NULL,'GET','/event/@id:[0-9]+/unregister','{"id":1}',NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (45,NULL,'DELETE','/api/carousel/delete/@id:[0-9]+','{"id":1}',NULL,NULL,'401',NULL,NULL);
INSERT INTO "Test" VALUES (46,NULL,'DELETE','/api/attribute/delete/@id:[0-9]+','{"id":1}',NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (47,NULL,'GET','/api/attributes-by-event-type/@id:[0-9]+','{"id":1}',NULL,NULL,'200',NULL,NULL);
INSERT INTO "Test" VALUES (48,NULL,'DELETE','/api/event/delete/@id:[0-9]+','{"id":1}',NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (49,NULL,'POST','/api/event/duplicate/@id:[0-9]+','{"id":1}','{"id":1}',NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (50,NULL,'GET','/api/event/@id:[0-9]+','{"id":1}',NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (51,NULL,'GET','/api/event-needs/@id:[0-9]+','{"id":1}',NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (52,NULL,'DELETE','/api/need/delete/@id:[0-9]+','{"id":1}',NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (53,NULL,'DELETE','/api/need/type/delete/@id:[0-9]+','{"id":1}',NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (54,NULL,'GET','/api/needs-by-need-type/@id:[0-9]+','{"id":1}',NULL,NULL,'200',NULL,NULL);
INSERT INTO "Test" VALUES (56,NULL,'DELETE','/api/navBar/deleteItem/@id:[0-9]+','{"id":1}',NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (57,NULL,'GET','/api/navBar/getItem/@id:[0-9]+','{"id":1}',NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (58,NULL,'GET','/api/personsInGroup/@id:[0-9]+','{"id":1}',NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (59,NULL,'POST','/api/registration/add/@personId:[0-9]+/@groupId:[0-9]+','{"personId":1, "groupId":1}','{"id":1}',NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (60,NULL,'POST','/api/registration/remove/@personId:[0-9]+/@groupId:[0-9]+','{"personId":1, "groupId":1}','{"id":1}',NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (61,NULL,'GET','/event/@id:[0-9]+/register','{"id":1}',NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (63,NULL,'POST','/designs/save',NULL,'{"id":1}',NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (64,NULL,'POST','/emails',NULL,'{"dayOfWeek":"zz"}',NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (65,NULL,'POST','/events/guest',NULL,'{"email":"zz"}',NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (66,NULL,'POST','/group/create',NULL,'{"name":"zz"}',NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (67,NULL,'POST','/import',NULL,'{"csvFile":"zz"}',NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (68,NULL,'POST','/user/presentation/edit',NULL,'{"content":"zz"}',NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (69,NULL,'POST','/surveys/create',NULL,'{"question":"zz"}',NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (70,NULL,'POST','/user/account',NULL,'{"id":1}',NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (71,NULL,'POST','/user/availabilities',NULL,'{"id":1}',NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (72,NULL,'POST','/user/groups',NULL,'{"id":1}',NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (73,NULL,'POST','/user/preferences',NULL,'{"id":1}',NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (74,NULL,'POST','/user/sign/in',NULL,'{"id":1}',NULL,'400',NULL,NULL);
INSERT INTO "Test" VALUES (75,NULL,'POST','/contact',NULL,'{"name":"zz","email":"user@myclub.foo", "message":"zz"}',NULL,'302',NULL,NULL);
INSERT INTO "Test" VALUES (76,NULL,'POST','/api/designs/vote',NULL,'{"id":1}',NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (77,NULL,'POST','/arwards',NULL,'{"id":1}',NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (78,NULL,'POST','/api/media/upload',NULL,'{"id":1}',NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (79,NULL,'POST','/api/surveys/reply',NULL,'{"id":1}',NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (80,NULL,'POST','/api/carousel/save',NULL,'{"id":1}',NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (81,NULL,'POST','/api/attribute/create',NULL,'{"id":1}',NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (82,NULL,'POST','/api/attribute/update',NULL,'{"id":1}',NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (83,NULL,'POST','/api/need/type/save',NULL,'{"id":1}',NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (84,NULL,'POST','/api/message/add',NULL,'{"id":1}',NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (85,NULL,'POST','/import/headers',NULL,'{"id":1}',NULL,'200',NULL,NULL);
INSERT INTO "Test" VALUES (86,NULL,'POST','/api/navBar/saveItem',NULL,'{"id":1}',NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (87,NULL,'POST','/api/event/save',NULL,'{"id":1}',NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (88,NULL,'POST','/api/event/updateSupply',NULL,'{"id":1}',NULL,'401',NULL,NULL);
INSERT INTO "Test" VALUES (89,NULL,'POST','/api/event/sendEmails',NULL,'{"id":1}',NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (90,NULL,'POST','/api/need/save',NULL,'{"id":1}',NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (91,NULL,'POST','/api/message/update',NULL,'{"id":1}',NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (92,NULL,'POST','/api/navBar/updatePositions',NULL,'{"id":1}',NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (93,22410,'POST','/user/sign/in',NULL,'{"email":"badEmail@myclub.foo","password":"wrongPassword" }',NULL,'400',NULL,NULL);
INSERT INTO "Test" VALUES (94,22420,'POST','/user/sign/in',NULL,'{"email":"webmaster@myclub.foo","password":"wrongPassword" }',NULL,'400',NULL,NULL);
INSERT INTO "Test" VALUES (95,22430,'POST','/user/sign/in',NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }',NULL,'302',NULL,NULL);
INSERT INTO "Test" VALUES (96,NULL,'GET','/user/sign/out',NULL,NULL,NULL,'302',NULL,NULL);
INSERT INTO "Test" VALUES (97,22450,'GET','/user/account',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','200',NULL,NULL);
INSERT INTO "Test" VALUES (98,22480,'GET','/user/availabilities',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','200',NULL,NULL);
INSERT INTO "Test" VALUES (99,22510,'GET','/user/groups',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','200','SELECT * From "Group"','[{"Id":1,"Name":"Webmaster","Inactivated":0,"SelfRegistration":0}]');
INSERT INTO "Test" VALUES (100,22530,'GET','/user/preferences',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','200',NULL,NULL);
INSERT INTO "Test" VALUES (101,22560,'GET','/user/statistics',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','200',NULL,NULL);
INSERT INTO "Test" VALUES (102,22570,'GET','/user/directory',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','200',NULL,NULL);
INSERT INTO "Test" VALUES (103,22640,'GET','/user/news',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','200',NULL,NULL);
INSERT INTO "Test" VALUES (104,22670,'GET','/webmaster',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','200',NULL,NULL);
INSERT INTO "Test" VALUES (105,22690,'GET','/dbbrowser',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','200',NULL,NULL);
INSERT INTO "Test" VALUES (106,22710,'GET','/navBar',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (107,22730,'GET','/arwards',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','200',NULL,NULL);
INSERT INTO "Test" VALUES (108,22750,'GET','/groups',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','200','SELECT * From "Group"','[{"Id":1,"Name":"Webmaster","Inactivated":0,"SelfRegistration":0}]');
INSERT INTO "Test" VALUES (109,22820,'GET','/eventTypes',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','200',NULL,NULL);
INSERT INTO "Test" VALUES (110,22840,'GET','/needs',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','200',NULL,NULL);
INSERT INTO "Test" VALUES (111,22770,'GET','/registration',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','200',NULL,NULL);
INSERT INTO "Test" VALUES (112,22860,'GET','/referents',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','200',NULL,NULL);
INSERT INTO "Test" VALUES (113,22880,'GET','/topPages',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','200',NULL,NULL);
INSERT INTO "Test" VALUES (114,22900,'GET','/crossTab',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','200',NULL,NULL);
INSERT INTO "Test" VALUES (115,22920,'GET','/logs',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','200',NULL,NULL);
INSERT INTO "Test" VALUES (116,22940,'GET','/lastVisits',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','200',NULL,NULL);
INSERT INTO "Test" VALUES (117,22790,'GET','/admin/webmaster/help',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','200',NULL,NULL);
INSERT INTO "Test" VALUES (118,22460,'POST','/user/account',NULL,'{"email":"webmaster%40myclub.foo", "firstName":"fn", "lastName":"ln", "nickName":"", "avatar":"%F0%9F%98%82"}','{"email":"webmaster@myclub.foo","password":"admin1234" }','302','SELECT Email, FirstName, LastName, NickName, Avatar From Person','[{"Email":"webmaster@myclub.foo","FirstName":"fn","LastName":"ln","NickName":"","Avatar":"🤔"}]');
INSERT INTO "Test" VALUES (119,22490,'POST','/user/availabilities',NULL,'{"availabilities":{"4":{"morning":"on"},"5":{"morning":"on"},"0":{"evening":"on"},"2":{"evening":"on"}}}','{"email":"webmaster@myclub.foo","password":"admin1234" }','302','SELECT Availabilities From Person','[{"Availabilities":"{\"4\":{\"morning\":\"on\"},\"5\":{\"morning\":\"on\"},\"0\":{\"evening\":\"on\"},\"2\":{\"evening\":\"on\"}}"}]');
INSERT INTO "Test" VALUES (120,22540,'POST','/user/preferences',NULL,'{"preferences":{"eventTypes":{"newEvent":{"enabled":"on"},"newArticle":{"enabled":"on","pollOnly":"on"}}}}','{"email":"webmaster@myclub.foo","password":"admin1234" }','302','SELECT Preferences From Person','[{"Preferences":"{\"eventTypes\":{\"newEvent\":{\"enabled\":\"on\"},\"newArticle\":{\"enabled\":\"on\",\"pollOnly\":\"on\"}}}"}]');
INSERT INTO "Test" VALUES (121,22800,'GET','/user/sign/out',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','302',NULL,NULL);
INSERT INTO "Test" VALUES (122,22580,'GET','/user/presentation/edit',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (123,22600,'POST','/user/presentation/edit',NULL,'{"content":"<p>my présentation</p>","location":"47.32326658122776,5.0348684191703805","inPresentationDirectory":"on"}','{"email":"webmaster@myclub.foo","password":"admin1234" }','302','SELECT Presentation, Location, InPresentationDirectory From Person','[{"Presentation":"<p>my présentation<\/p>","Location":"47.32326658122776,5.0348684191703805","InPresentationDirectory":1}]');
INSERT INTO "Test" VALUES (124,22590,'GET','/user/presentation/edit',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','200',NULL,NULL);
INSERT INTO "Test" VALUES (125,22610,'GET','/user/directory?group=1',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (126,22620,'GET','/user/directory?group=1',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','200',NULL,NULL);
INSERT INTO "Test" VALUES (127,22630,'GET','/user/news',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (128,22650,'GET','/user/news?from=month',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','200',NULL,NULL);
INSERT INTO "Test" VALUES (129,22660,'GET','/webmaster',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (130,22680,'GET','/dbbrowser',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (131,22700,'GET','/navBar',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (132,22720,'GET','/arwards',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (133,22740,'GET','/groups',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (134,22760,'GET','/registration',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (135,22780,'GET','/admin/webmaster/help',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (136,22440,'GET','/user/account',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (137,22470,'GET','/user/availabilities',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (138,22500,'GET','/user/groups',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (139,22520,'GET','/user/preferences',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (140,22550,'GET','/user/statistics',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (141,22810,'GET','/eventTypes',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (142,22830,'GET','/needs',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (143,22850,'GET','/referents',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (144,22870,'GET','/topPages',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (145,22890,'GET','/crossTab',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (146,22910,'GET','/logs',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (147,22930,'GET','/lastVisits',NULL,NULL,NULL,'403',NULL,NULL);
INSERT INTO "Test" VALUES (148,1000,'PUT','/',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (149,1010,'PUT','/admin',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (150,1020,'PUT','/admin/help',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (151,1030,'PUT','/admin/webmaster/help',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (152,1040,'PUT','/analytics',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (153,1050,'PUT','/api/attribute/create',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (154,1060,'PUT','/api/attribute/delete/1',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (155,1070,'PUT','/api/attribute/update',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (156,1080,'PUT','/api/attributes-by-event-type/1',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (157,1090,'PUT','/api/attributes/list',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (158,1100,'PUT','/api/author/1',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (159,1110,'PUT','/api/carousel/1',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (160,1120,'PUT','/api/carousel/delete/1',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (161,1130,'PUT','/api/carousel/save',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (162,1140,'PUT','/api/designs/vote',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (163,1150,'PUT','/api/event-needs/1',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (164,1160,'PUT','/api/event/1',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (165,1170,'PUT','/api/event/delete/1',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (166,1180,'PUT','/api/event/duplicate/@id',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (167,1190,'PUT','/api/event/save',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (168,1200,'PUT','/api/event/sendEmails',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (169,1210,'PUT','/api/event/updateSupply',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (170,1220,'PUT','/api/lastVersion',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (171,1230,'PUT','/api/media/delete/1/1/zz',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (172,1240,'PUT','/api/media/upload',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (173,1250,'PUT','/api/message/add',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (174,1260,'PUT','/api/message/delete',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (175,1270,'PUT','/api/message/update',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (176,1280,'PUT','/api/navBar/deleteItem/1',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (177,1290,'PUT','/api/navBar/getItem/1',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (178,1300,'PUT','/api/navBar/saveItem',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (179,1310,'PUT','/api/navBar/updatePositions',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (180,1320,'PUT','/api/needs-by-need-type/1',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (181,1330,'PUT','/api/need/delete/1',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (182,1340,'PUT','/api/need/save',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (183,1350,'PUT','/api/need/type/delete/1',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (184,1360,'PUT','/api/need/type/save',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (185,1370,'PUT','/api/personsInGroup/1',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (186,1380,'PUT','/api/registration/add/1/1',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (187,1390,'PUT','/api/registration/remove/1/1',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (188,1400,'PUT','/api/surveys/reply',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (189,1410,'PUT','/api/surveys/reply/1',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (190,1420,'PUT','/article/1',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (191,1430,'PUT','/article/create',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (192,1440,'PUT','/article/delete/1',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (193,1450,'PUT','/articles',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (194,1460,'PUT','/articles-rss.xml',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (195,1470,'PUT','/articles/crosstab',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (196,1480,'PUT','/arwards',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (197,1490,'PUT','/contact',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (198,1500,'PUT','/contact/event/1',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (199,1510,'PUT','/crossTab',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (200,1520,'PUT','/data/media/1/1/zz',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (201,1530,'PUT','/dbbrowser',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (202,1540,'PUT','/dbbrowser/zz',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (203,1550,'PUT','/dbbrowser/zz/create',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (204,1560,'PUT','/dbbrowser/zz/delete/1',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (205,1570,'PUT','/dbbrowser/zz/edit/1',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (206,1580,'PUT','/designer',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (207,1590,'PUT','/designer/help',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (208,1600,'PUT','/designs',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (209,1610,'PUT','/designs/create',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (210,1620,'PUT','/designs/save',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (211,1630,'PUT','/emails',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (212,1640,'PUT','/emails/article/1',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (213,1650,'PUT','/event/1',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (214,1660,'PUT','/event/1/0123456789abcdef0123456789abcdef',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (215,1670,'PUT','/event/1/register',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (216,1680,'PUT','/event/1/unregister',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (217,1690,'PUT','/event/chat/1',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (218,1700,'PUT','/event/location',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (219,1710,'PUT','/eventManager',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (220,1720,'PUT','/eventManager/help',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (221,1730,'PUT','/eventTypes',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (222,1740,'PUT','/eventTypes/create',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (223,1750,'PUT','/eventTypes/delete/1',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (224,1760,'PUT','/eventTypes/edit/1',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (225,1770,'PUT','/events-rss.xml',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (226,1780,'PUT','/events/crosstab',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (227,1790,'PUT','/events/guest',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (228,1800,'PUT','/ffa/search',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (229,1810,'PUT','/group/create',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (230,1820,'PUT','/group/delete/1',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (231,1830,'PUT','/group/edit/1',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (232,1840,'PUT','/groups',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (233,1850,'PUT','/help',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (234,1860,'PUT','/import',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (235,1870,'PUT','/import/headers',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (236,1880,'PUT','/installations',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (237,1890,'PUT','/lastVisits',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (238,1900,'PUT','/legal/notice',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (239,1910,'PUT','/logs',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (240,1920,'PUT','/media/gpxViewer',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (241,1930,'PUT','/media/list',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (242,1940,'PUT','/media/upload',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (243,1950,'PUT','/navBar',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (244,1960,'PUT','/navBar/show/article/1',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (245,1970,'PUT','/navBar/show/arwards',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (246,1980,'PUT','/needs',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (247,1990,'PUT','/nextEvents',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (248,2000,'PUT','/personManager',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (249,2010,'PUT','/personManager/help',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (250,2020,'PUT','/persons',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (251,2030,'PUT','/persons/create',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (252,2040,'PUT','/persons/delete/1',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (253,2050,'PUT','/persons/edit/1',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (254,2060,'PUT','/publish/article/1',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (255,2070,'PUT','/redactor',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (256,2080,'PUT','/redactor/help',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (257,2090,'PUT','/referents',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (258,2100,'PUT','/registration',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (259,2110,'PUT','/registration/groups/1',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (260,2120,'PUT','/settings',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (261,2130,'PUT','/sitemap.xml',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (262,2140,'PUT','/surveys/add/1',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (263,2150,'PUT','/surveys/create',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (264,2160,'PUT','/surveys/results/1',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (265,2170,'PUT','/topArticles',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (266,2180,'PUT','/topPages',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (267,2190,'PUT','/user',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (268,2200,'PUT','/user/account',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (269,2210,'PUT','/user/availabilities',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (270,2220,'PUT','/user/directory',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (271,2230,'PUT','/user/forgotPassword/webmaster@myclub.foo',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (272,2240,'PUT','/user/groups',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (273,2250,'PUT','/user/help',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (274,2260,'PUT','/user/map',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (275,2270,'PUT','/user/news',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (276,2280,'PUT','/user/notepad',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (277,2290,'PUT','/user/preferences',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (278,2300,'PUT','/user/presentation/1',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (279,2310,'PUT','/user/presentation/edit',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (280,2320,'PUT','/user/setPassword/0123456789abcdef0123456789abcdef',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (281,2330,'PUT','/user/sign/in',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (282,2340,'PUT','/user/sign/out',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (283,2350,'PUT','/user/statistics',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (284,2360,'PUT','/visitorInsights',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (285,2370,'PUT','/visitorInsights/help',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (286,2380,'PUT','/visitors/graf',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (287,2390,'PUT','/webmaster',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (288,2400,'PUT','/weekEvents',NULL,NULL,NULL,'404',NULL,NULL);
INSERT INTO "Test" VALUES (289,11000,'GET','/',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','200',NULL,NULL);
INSERT INTO "Test" VALUES (290,11010,'GET','/admin',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','302',NULL,NULL);
INSERT INTO "Test" VALUES (291,11020,'GET','/admin/help',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','200',NULL,NULL);
INSERT INTO "Test" VALUES (292,11030,'GET','/admin/webmaster/help',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','200',NULL,NULL);
INSERT INTO "Test" VALUES (293,11040,'GET','/analytics',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (294,11050,'POST','/api/attribute/create',NULL,'{"name":"attribute name", "detail":"attribute detail", "color":"#112233" }','{"email":"webmaster@myclub.foo","password":"admin1234" }','200','SELECT * From Attribute','[{"Id":1,"Name":"attribute name","Detail":"attribute detail","Color":"#112233"}]');
INSERT INTO "Test" VALUES (295,11072,'DELETE','/api/attribute/delete/1',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','200','SELECT * From Attribute','[]');
INSERT INTO "Test" VALUES (296,11070,'POST','/api/attribute/update',NULL,'{"id":1, "name":"attribute name updated", "detail":"attribute detail updated", "color":"#223344" }','{"email":"webmaster@myclub.foo","password":"admin1234" }','200','SELECT * From Attribute','[{"Id":1,"Name":"attribute name updated","Detail":"attribute detail updated","Color":"#223344"}]');
INSERT INTO "Test" VALUES (297,11080,'GET','/api/attributes-by-event-type/1',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','200',NULL,NULL);
INSERT INTO "Test" VALUES (298,11090,'GET','/api/attributes/list',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','200',NULL,NULL);
INSERT INTO "Test" VALUES (299,11100,'GET','/api/author/1',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','200',NULL,NULL);
INSERT INTO "Test" VALUES (300,11110,'GET','/api/carousel/1',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (301,11120,'DELETE','/api/carousel/delete/1',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','404',NULL,NULL);
INSERT INTO "Test" VALUES (302,11130,'POST','/api/carousel/save',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','400',NULL,NULL);
INSERT INTO "Test" VALUES (303,11140,'POST','/api/designs/vote',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (304,11150,'GET','/api/event-needs/1',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (305,11160,'GET','/api/event/1',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (306,11170,'DELETE','/api/event/delete/1',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (307,11180,'POST','/api/event/duplicate/1',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (308,11190,'POST','/api/event/save',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (309,11200,'POST','/api/event/sendEmails',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (310,11210,'POST','/api/event/updateSupply',NULL,'{"eventId":1, "needId":1, "supply":1}','{"email":"webmaster@myclub.foo","password":"admin1234" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (311,11220,'GET','/api/lastVersion',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','200',NULL,NULL);
INSERT INTO "Test" VALUES (312,11230,'DELETE','/api/media/delete/1/1/zz',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (313,11240,'POST','/api/media/upload',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (314,11250,'POST','/api/message/add',NULL,'{"eventId":1, "text":"new message"}','{"email":"webmaster@myclub.foo","password":"admin1234" }','400',NULL,NULL);
INSERT INTO "Test" VALUES (315,11260,'DELETE','/api/message/delete',NULL,'{"messageId":1}','{"email":"webmaster@myclub.foo","password":"admin1234" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (316,11270,'POST','/api/message/update',NULL,'{"messageId":1, "text":"message updated"}','{"email":"webmaster@myclub.foo","password":"admin1234" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (317,11280,'DELETE','/api/navBar/deleteItem/1',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (318,11290,'GET','/api/navBar/getItem/1',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (319,11300,'POST','/api/navBar/saveItem',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (320,11310,'POST','/api/navBar/updatePositions',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (321,11320,'GET','/api/needs-by-need-type/1',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','200',NULL,NULL);
INSERT INTO "Test" VALUES (322,11330,'DELETE','/api/need/delete/1',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (323,11340,'POST','/api/need/save',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (324,11350,'DELETE','/api/need/type/delete/1',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (325,11360,'POST','/api/need/type/save',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','403',NULL,NULL);
INSERT INTO "Test" VALUES (326,11370,'GET','/api/personsInGroup/1',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','200',NULL,NULL);
INSERT INTO "Test" VALUES (327,11380,'POST','/api/registration/add/1/1',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','400',NULL,NULL);
INSERT INTO "Test" VALUES (328,11390,'POST','/api/registration/remove/1/1',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','400',NULL,NULL);
INSERT INTO "Test" VALUES (329,11400,'POST','/api/surveys/reply',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','400',NULL,NULL);
INSERT INTO "Test" VALUES (330,11410,'GET','/api/surveys/reply/1',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','400',NULL,NULL);
INSERT INTO "Test" VALUES (331,11420,'GET','/article/1',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','404',NULL,NULL);
INSERT INTO "Test" VALUES (332,11430,'GET','/article/create',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','404',NULL,NULL);
INSERT INTO "Test" VALUES (333,11440,'DELETE','/article/delete/1',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','404',NULL,NULL);
INSERT INTO "Test" VALUES (334,11450,'GET','/articles',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','404',NULL,NULL);
INSERT INTO "Test" VALUES (335,11460,'GET','/articles-rss.xml',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','404',NULL,NULL);
INSERT INTO "Test" VALUES (336,11470,'GET','/articles/crosstab',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','404',NULL,NULL);
INSERT INTO "Test" VALUES (337,11480,'GET','/arwards',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','404',NULL,NULL);
INSERT INTO "Test" VALUES (338,11490,'GET','/contact',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','404',NULL,NULL);
INSERT INTO "Test" VALUES (339,11500,'GET','/contact/event/1',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','404',NULL,NULL);
INSERT INTO "Test" VALUES (340,11510,'GET','/crossTab',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','404',NULL,NULL);
INSERT INTO "Test" VALUES (341,11520,'GET','/data/media/1/1/zz',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','404',NULL,NULL);
INSERT INTO "Test" VALUES (342,11530,'GET','/dbbrowser',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','404',NULL,NULL);
INSERT INTO "Test" VALUES (343,11540,'GET','/dbbrowser/zz',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','404',NULL,NULL);
INSERT INTO "Test" VALUES (344,11550,'GET','/dbbrowser/zz/create',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','404',NULL,NULL);
INSERT INTO "Test" VALUES (345,11560,'DELETE','/dbbrowser/zz/delete/1',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','404',NULL,NULL);
INSERT INTO "Test" VALUES (346,11570,'GET','/dbbrowser/zz/edit/1',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','404',NULL,NULL);
INSERT INTO "Test" VALUES (347,11580,'GET','/designer',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','404',NULL,NULL);
INSERT INTO "Test" VALUES (348,11590,'GET','/designer/help',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','404',NULL,NULL);
INSERT INTO "Test" VALUES (349,11600,'GET','/designs',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','404',NULL,NULL);
INSERT INTO "Test" VALUES (350,11610,'GET','/designs/create',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','404',NULL,NULL);
INSERT INTO "Test" VALUES (351,11620,'POST','/designs/save',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','404',NULL,NULL);
INSERT INTO "Test" VALUES (352,11630,'GET','/emails',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','404',NULL,NULL);
INSERT INTO "Test" VALUES (353,11640,'GET','/emails/article/1',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','404',NULL,NULL);
INSERT INTO "Test" VALUES (354,11650,'GET','/event/1',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','404',NULL,NULL);
INSERT INTO "Test" VALUES (355,11660,'GET','/event/1/0123456789abcdef0123456789abcdef',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','404',NULL,NULL);
INSERT INTO "Test" VALUES (356,11670,'GET','/event/1/register',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','404',NULL,NULL);
INSERT INTO "Test" VALUES (357,11680,'GET','/event/1/unregister',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','404',NULL,NULL);
INSERT INTO "Test" VALUES (358,11690,'GET','/event/chat/1',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','404',NULL,NULL);
INSERT INTO "Test" VALUES (359,11700,'GET','/event/location',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','404',NULL,NULL);
INSERT INTO "Test" VALUES (360,11710,'GET','/eventManager',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','404',NULL,NULL);
INSERT INTO "Test" VALUES (361,11720,'GET','/eventManager/help',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','404',NULL,NULL);
INSERT INTO "Test" VALUES (362,11730,'GET','/eventTypes',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','404',NULL,NULL);
INSERT INTO "Test" VALUES (363,11740,'GET','/eventTypes/create',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','404',NULL,NULL);
INSERT INTO "Test" VALUES (364,11750,'DELETE','/eventTypes/delete/1',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','404',NULL,NULL);
INSERT INTO "Test" VALUES (365,11760,'GET','/eventTypes/edit/1',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','404',NULL,NULL);
INSERT INTO "Test" VALUES (366,11770,'GET','/events-rss.xml',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','404',NULL,NULL);
INSERT INTO "Test" VALUES (367,11780,'GET','/events/crosstab',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','404',NULL,NULL);
INSERT INTO "Test" VALUES (368,11790,'GET','/events/guest',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','404',NULL,NULL);
INSERT INTO "Test" VALUES (369,11800,'GET','/ffa/search',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','404',NULL,NULL);
INSERT INTO "Test" VALUES (370,11810,'GET','/group/create',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','404',NULL,NULL);
INSERT INTO "Test" VALUES (371,11820,'DELETE','/group/delete/1',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','404',NULL,NULL);
INSERT INTO "Test" VALUES (372,11830,'GET','/group/edit/1',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','404',NULL,NULL);
INSERT INTO "Test" VALUES (373,11840,'GET','/groups',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','404',NULL,NULL);
INSERT INTO "Test" VALUES (374,11850,'GET','/help',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','404',NULL,NULL);
INSERT INTO "Test" VALUES (375,11860,'GET','/import',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','404',NULL,NULL);
INSERT INTO "Test" VALUES (376,11870,'POST','/import/headers',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','404',NULL,NULL);
INSERT INTO "Test" VALUES (377,11880,'GET','/installations',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','404',NULL,NULL);
INSERT INTO "Test" VALUES (378,11890,'GET','/lastVisits',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','404',NULL,NULL);
INSERT INTO "Test" VALUES (379,11900,'GET','/legal/notice',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','404',NULL,NULL);
INSERT INTO "Test" VALUES (380,11910,'GET','/logs',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','404',NULL,NULL);
INSERT INTO "Test" VALUES (381,11920,'GET','/media/gpxViewer',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','404',NULL,NULL);
INSERT INTO "Test" VALUES (382,11930,'GET','/media/list',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','404',NULL,NULL);
INSERT INTO "Test" VALUES (383,11940,'GET','/media/upload',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','404',NULL,NULL);
INSERT INTO "Test" VALUES (384,11950,'GET','/navBar',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','404',NULL,NULL);
INSERT INTO "Test" VALUES (385,11960,'GET','/navBar/show/article/1',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','404',NULL,NULL);
INSERT INTO "Test" VALUES (386,11970,'GET','/navBar/show/arwards',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','404',NULL,NULL);
INSERT INTO "Test" VALUES (387,11980,'GET','/needs',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','404',NULL,NULL);
INSERT INTO "Test" VALUES (388,11990,'GET','/nextEvents',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','404',NULL,NULL);
INSERT INTO "Test" VALUES (389,12000,'GET','/personManager',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','404',NULL,NULL);
INSERT INTO "Test" VALUES (390,12010,'GET','/personManager/help',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','404',NULL,NULL);
INSERT INTO "Test" VALUES (391,12020,'GET','/persons',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','404',NULL,NULL);
INSERT INTO "Test" VALUES (392,12030,'GET','/persons/create',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','404',NULL,NULL);
INSERT INTO "Test" VALUES (393,12040,'DELETE','/persons/delete/1',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','404',NULL,NULL);
INSERT INTO "Test" VALUES (394,12050,'GET','/persons/edit/1',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','404',NULL,NULL);
INSERT INTO "Test" VALUES (395,12060,'GET','/publish/article/1',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','404',NULL,NULL);
INSERT INTO "Test" VALUES (396,12070,'GET','/redactor',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','404',NULL,NULL);
INSERT INTO "Test" VALUES (397,12080,'GET','/redactor/help',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','404',NULL,NULL);
INSERT INTO "Test" VALUES (398,12090,'GET','/referents',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','404',NULL,NULL);
INSERT INTO "Test" VALUES (399,12100,'GET','/registration',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','404',NULL,NULL);
INSERT INTO "Test" VALUES (400,12110,'GET','/registration/groups/1',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','404',NULL,NULL);
INSERT INTO "Test" VALUES (401,12120,'GET','/settings',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','404',NULL,NULL);
INSERT INTO "Test" VALUES (402,12130,'GET','/sitemap.xml',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','404',NULL,NULL);
INSERT INTO "Test" VALUES (403,12140,'GET','/surveys/add/1',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','404',NULL,NULL);
INSERT INTO "Test" VALUES (404,12150,'POST','/surveys/create',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','404',NULL,NULL);
INSERT INTO "Test" VALUES (405,12160,'GET','/surveys/results/1',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','404',NULL,NULL);
INSERT INTO "Test" VALUES (406,12170,'GET','/topArticles',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','404',NULL,NULL);
INSERT INTO "Test" VALUES (407,12180,'GET','/topPages',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','404',NULL,NULL);
INSERT INTO "Test" VALUES (408,12190,'GET','/user',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','404',NULL,NULL);
INSERT INTO "Test" VALUES (409,12200,'GET','/user/account',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','404',NULL,NULL);
INSERT INTO "Test" VALUES (410,12210,'GET','/user/availabilities',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','404',NULL,NULL);
INSERT INTO "Test" VALUES (411,12220,'GET','/user/directory',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','404',NULL,NULL);
INSERT INTO "Test" VALUES (412,12230,'GET','/user/forgotPassword/webmaster@myclub.foo',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','404',NULL,NULL);
INSERT INTO "Test" VALUES (413,12240,'GET','/user/groups',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','404',NULL,NULL);
INSERT INTO "Test" VALUES (414,12250,'GET','/user/help',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','404',NULL,NULL);
INSERT INTO "Test" VALUES (415,12260,'GET','/user/map',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','404',NULL,NULL);
INSERT INTO "Test" VALUES (416,12270,'GET','/user/news',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','404',NULL,NULL);
INSERT INTO "Test" VALUES (417,12280,'GET','/user/notepad',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','404',NULL,NULL);
INSERT INTO "Test" VALUES (418,12290,'GET','/user/preferences',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','404',NULL,NULL);
INSERT INTO "Test" VALUES (419,12300,'GET','/user/presentation/1',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','404',NULL,NULL);
INSERT INTO "Test" VALUES (420,12310,'GET','/user/presentation/edit',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','404',NULL,NULL);
INSERT INTO "Test" VALUES (421,12320,'GET','/user/setPassword/0123456789abcdef0123456789abcdef',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','404',NULL,NULL);
INSERT INTO "Test" VALUES (422,12330,'GET','/user/sign/in',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','404',NULL,NULL);
INSERT INTO "Test" VALUES (423,12340,'GET','/user/sign/out',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','404',NULL,NULL);
INSERT INTO "Test" VALUES (424,12350,'GET','/user/statistics',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','404',NULL,NULL);
INSERT INTO "Test" VALUES (425,12360,'GET','/visitorInsights',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','404',NULL,NULL);
INSERT INTO "Test" VALUES (426,12370,'GET','/visitorInsights/help',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','404',NULL,NULL);
INSERT INTO "Test" VALUES (427,12380,'GET','/visitors/graf',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','404',NULL,NULL);
INSERT INTO "Test" VALUES (428,12390,'GET','/webmaster',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','404',NULL,NULL);
INSERT INTO "Test" VALUES (429,12400,'GET','/weekEvents',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','404',NULL,NULL);
INSERT INTO "Test" VALUES (430,11422,'POST','/article/1',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','404',NULL,NULL);
INSERT INTO "Test" VALUES (431,11482,'POST','/arwards',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','404',NULL,NULL);
INSERT INTO "Test" VALUES (432,11492,'POST','/contact',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','404',NULL,NULL);
INSERT INTO "Test" VALUES (433,11552,'POST','/dbbrowser/zz/create',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','404',NULL,NULL);
INSERT INTO "Test" VALUES (434,11572,'POST','/dbbrowser/zz/edit/1',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','404',NULL,NULL);
INSERT INTO "Test" VALUES (435,11632,'POST','/emails',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','404',NULL,NULL);
INSERT INTO "Test" VALUES (436,11762,'POST','/eventTypes/edit/1',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','404',NULL,NULL);
INSERT INTO "Test" VALUES (437,11792,'POST','/events/guest',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','404',NULL,NULL);
INSERT INTO "Test" VALUES (438,11812,'POST','/group/create',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','404',NULL,NULL);
INSERT INTO "Test" VALUES (439,11832,'POST','/group/edit/1',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','404',NULL,NULL);
INSERT INTO "Test" VALUES (440,11862,'POST','/import',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','404',NULL,NULL);
INSERT INTO "Test" VALUES (441,12052,'POST','/persons/edit/1',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','404',NULL,NULL);
INSERT INTO "Test" VALUES (442,12062,'POST','/publish/article/1',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','404',NULL,NULL);
INSERT INTO "Test" VALUES (443,12122,'POST','/settings',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','404',NULL,NULL);
INSERT INTO "Test" VALUES (444,12202,'POST','/user/account',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','404',NULL,NULL);
INSERT INTO "Test" VALUES (445,12212,'POST','/user/availabilities',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','404',NULL,NULL);
INSERT INTO "Test" VALUES (446,12242,'POST','/user/groups',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','404',NULL,NULL);
INSERT INTO "Test" VALUES (447,12282,'POST','/user/notepad',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','404',NULL,NULL);
INSERT INTO "Test" VALUES (448,12292,'POST','/user/preferences',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','404',NULL,NULL);
INSERT INTO "Test" VALUES (449,12312,'POST','/user/presentation/edit',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','404',NULL,NULL);
INSERT INTO "Test" VALUES (450,12322,'POST','/user/setPassword/0123456789abcdef0123456789abcdef',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','404',NULL,NULL);
INSERT INTO "Test" VALUES (451,12332,'POST','/user/sign/in',NULL,NULL,'{"email":"webmaster@myclub.foo","password":"admin1234" }','404',NULL,NULL);
COMMIT;
