<?php

declare(strict_types=1);

namespace app\models\database\migrators;

use PDO;
use app\modules\Common\interfaces\DatabaseMigratorInterface;

final class V88ToV89Migrator implements DatabaseMigratorInterface
{
    public function upgrade(PDO $pdo, int $currentVersion): int
    {
        $pdo->exec(<<<SQL
INSERT OR REPLACE INTO Languages (Name, en_US, fr_FR, pl_PL) VALUES
('import.title',
'Import CSV',
'Import CSV',
'Import CSV'),
('import.error.invalid_file',
'Please select a valid CSV file',
'Veuillez sélectionner un fichier CSV valide',
'Wybierz prawidłowy plik CSV'),
('import.error.invalid_email',
'Line {line}: invalid email address {email}.',
'Ligne {line} : adresse email invalide {email}.',
'Wiersz {line}: nieprawidłowy adres e-mail {email}.'),
('import.error.invalid_custom_value',
'Line {line}: invalid value "{value}" for field "{field}", ignored.',
'Ligne {line} : valeur « {value} » invalide pour le champ « {field} », ignorée.',
'Wiersz {line}: nieprawidłowa wartość „{value}” dla pola „{field}”, pominięto.'),
('import.result.title',
'Import result:',
'Résultat de l''import :',
'Wynik importu:'),
('import.result.created',
'New records:',
'Nouveaux enregistrements :',
'Nowe rekordy:'),
('import.result.updated',
'Updated records:',
'Enregistrements mis à jour :',
'Zaktualizowane rekordy:'),
('import.result.deactivated',
'Deactivated records:',
'Enregistrements inactivés :',
'Dezaktywowane rekordy:'),
('import.result.errors',
'Errors:',
'Erreurs :',
'Błędy:'),
('import.result.errors_detail',
'Error details:',
'Détail des erreurs :',
'Szczegóły błędów:'),
('import.result.success',
'Import completed successfully:',
'Import terminé avec succès :',
'Import zakończony pomyślnie:'),
('import.result.details',
'Details:',
'Détails :',
'Szczegóły:'),
('import.form.csv_file',
'CSV file',
'Fichier CSV',
'Plik CSV'),
('import.form.header_row',
'Header row',
'Ligne des en-têtes',
'Wiersz nagłówków'),
('import.form.mapping_title',
'Column mapping',
'Mapping des colonnes',
'Mapowanie kolumn'),
('import.form.custom_fields_title',
'Custom fields (optional)',
'Champs personnalisés (facultatifs)',
'Pola niestandardowe (opcjonalne)'),
('import.form.email',
'Email',
'Email',
'E-mail'),
('import.form.firstname',
'First name',
'Prénom',
'Imię'),
('import.form.lastname',
'Last name',
'Nom',
'Nazwisko'),
('import.form.phone',
'Phone',
'Téléphone',
'Telefon'),
('import.form.select_column',
'Select a column',
'Sélectionnez une colonne',
'Wybierz kolumnę'),
('import.form.email_header_warning',
'⚠️ The selected column has no header name. Email is required for the import.',
'⚠️ La colonne sélectionnée n''a pas de nom d''en-tête. L''email est obligatoire pour l''import.',
'⚠️ Wybrana kolumna nie ma nazwy nagłówka. E-mail jest wymagany do importu.'),
('import.form.submit',
'Import',
'Importer',
'Importuj'),
('import.form.submitting',
'Import in progress...',
'Import en cours...',
'Trwa importowanie...'),
('import.js.invalid_extension',
'The file must be in .csv format',
'Le fichier doit être au format .csv',
'Plik musi mieć format .csv'),
('import.js.invalid_type',
'File type not allowed.',
'Type de fichier non autorisé.',
'Niedozwolony typ pliku.'),
('import.js.file_too_large',
'File too large (max {max})',
'Fichier trop volumineux (max {max})',
'Plik jest za duży (maks. {max})'),
('import.js.unknown_error',
'Unknown error',
'Erreur inconnue',
'Nieznany błąd'),
('import.js.read_error',
'Error while reading the file.',
'Erreur lors de la lecture du fichier.',
'Błąd podczas odczytu pliku.'),
('import.js.column_option',
'{header} (column {index})',
'{header} (colonne {index})',
'{header} (kolumna {index})');
SQL);

        return 89;
    }
}
